[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "mkdocstrings"
version = "0.9.1"
description = "Automatic documentation from sources, for mkdocs."
authors = ["Timothée Mazzucotelli <pawamoy@pm.me>"]
license = "ISC License"
readme = "README.md"
repository = "https://github.com/pawamoy/mkdocstrings"
homepage = "https://github.com/pawamoy/mkdocstrings"
keywords = ["mkdocs", "mkdocs-plugin", "docstrings", "autodoc", "documentation"]
packages = [ { include = "mkdocstrings", from = "src" } ]
include = [
    "README.md",
    "pyproject.toml"
]

[tool.poetry.dependencies]
python = "^3.6"
mkdocs = "^1.1"
beautifulsoup4 = "^4.8.2"
pytkdocs = "^0.1.1"

[tool.poetry.dev-dependencies]
bandit = "^1.5"
black = { version = "*", allow-prereleases = true }
coverage = "^5.0.4"
flake8 = "^3.6"
git-changelog = "^0.2.0"
ipython = "^7.2"
isort = { version = "^4.3", extras = ["pyproject"] }
jinja2-cli = "^0.7.0"
mkdocs = "^1.0"
mkdocs-material = "^4.5"
pylint = { git = "https://github.com/PyCQA/pylint" }
pytest = "^4.3"
pytest-cov = "^2.8"
pytest-sugar = "^0.9.2"
pytest-xdist = "^1.26"
safety = "^1.8"
toml = "^0.10.0"

[tool.poetry.plugins."mkdocs.plugins"]
mkdocstrings = "mkdocstrings.plugin:MkdocstringsPlugin"

[tool.black]
line-length = 120

[tool.isort]
line_length = 120
not_skip = "__init__.py"
multi_line_output = 3
force_single_line = false
balanced_wrapping = true
default_section = "THIRDPARTY"
known_first_party = "mkdocstrings"
include_trailing_comma = true

[tool.pylint.options]
disable = """
  bad-continuation,
  too-many-lines,
  too-many-public-methods,
  too-many-locals,
  too-many-statements,
  too-many-arguments,
  too-many-instance-attributes,
  too-many-branches,
  too-few-public-methods,
  duplicate-code
"""
max-line-length = "120"
