language: python
services:
- docker
os: linux
python:
  - "3.6"
  - "3.7"
  - "3.8"
before_install:
  - python -m pip install --upgrade pip
  - jq -r '.default | to_entries[] | .key + .value.version' Pipfile.lock > requirements.txt
  - jq -r '.develop | to_entries[] | .key + .value.version' Pipfile.lock > requirements.txt
install:
  - pip install tox
script:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then export TOXENV=py36; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.7 ]]; then export TOXENV=py37; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.8 ]]; then export TOXENV=py38; fi
  - tox
after_script:
  - rm -rf requirements.txt

jobs:
  include:
  - stage: Code style
    env: TOXENV=style
    before_install:
      - python -m pip install --upgrade pip
    install:
      - pip install tox
    script:
      - tox

  - stage: Lint documentation
    install:
    - gem install mdl
    script:
    - mdl docs --rules "~MD013,~MD025"

  - stage: Deploy
    script:
      - jq -r '.default | to_entries[] | .key + .value.version' Pipfile.lock > requirements.txt
      - pip install -r requirements.txt
      - sed -i "s/development/$TRAVIS_COMMIT/g" wilfred/version.py
      - sed -i "s/YYYY-MM-DD/`git log -1 --format="%at" | xargs -I{} date -d @{} +%Y-%m-%d`/g" wilfred/version.py
      - rm -rf requirements.txt
    deploy:
      - provider: pypi
        skip_cleanup: true
        user: __token__
        password:
          secure: Cud1CEGJO/HW5bhceLt78DLeBGV6cdK28fLSD7Td5XWe3PVuYvvDBNkNRxtYvzGUqg1zi/768Rl5rSX9y3wuC4/5qZVE9JJrF0F0RVGnSzkemYnq2JZVcdQYKKXEagRH42jy13mu19HCpGy1861+8GSmIrq4TdEWGFvHMQQKBLeYf6A3Zf/rRqLBbPIpXvfs8YnNXdzZYt1kOhf09WpH0yQOK4Hb/UiKzYFToJhGhklmhRjsq/tcMIdVY9Cbd0qKU7VDB48itY1ARvjGZB6+Z4BK+AHPGBQX5zB8Eqzd/R4d1fFnNk3eHCdIuwDllWJFu03U2UnH4+ie8lwEUV4VqkLZ9quvWRaJDKdGjKX9iRkitVMvIW2y7CMbQE42JP6PssJLiYdvcX3GeiLR8q8uqLHhwHvffOcM5LLnFy8duE7nQkzIlQGz3ni2jMbZqDfriJqCYmaGRaThqcgU6eDuWvKzu57pqlf9n1UX6m1fM4ITQtTtOk6mi8gRBkt4tW2jCw+6ovdrjgnfzGNwnoZABiZKIQibC0PxBByhAjbO3E2M1/TTyuqTx2MzmK4QiLHs0pikFH4samOYEjCvVsVyn3oKRThjNCPikqXESQULwd1qzTMUC14tf//ZJZATlXNKQmiQ+o95gz0uQe6912MLz0XKKNyGl5ILgEUBvsLYM+Y=
        distributions: "sdist bdist_wheel"
        on:
          tags: true
