# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(608, 609)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.backendBox = QtWidgets.QComboBox(self.centralwidget)
        self.backendBox.setEditable(False)
        self.backendBox.setObjectName("backendBox")
        self.horizontalLayout_2.addWidget(self.backendBox)
        self.idEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.idEdit.setObjectName("idEdit")
        self.horizontalLayout_2.addWidget(self.idEdit)
        self.loadButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadButton.setObjectName("loadButton")
        self.horizontalLayout_2.addWidget(self.loadButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.contentEdit = QtWidgets.QPlainTextEdit(self.tab)
        self.contentEdit.setReadOnly(True)
        self.contentEdit.setObjectName("contentEdit")
        self.verticalLayout_2.addWidget(self.contentEdit)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.previewEdit = QtWidgets.QTextEdit(self.tab_2)
        self.previewEdit.setReadOnly(True)
        self.previewEdit.setObjectName("previewEdit")
        self.verticalLayout_3.addWidget(self.previewEdit)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.historyTable = QtWidgets.QTableWidget(self.tab_3)
        self.historyTable.setObjectName("historyTable")
        self.historyTable.setColumnCount(4)
        self.historyTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.historyTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.historyTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.historyTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.historyTable.setHorizontalHeaderItem(3, item)
        self.verticalLayout_4.addWidget(self.historyTable)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.nbRevisionsLabel = QtWidgets.QLabel(self.tab_3)
        self.nbRevisionsLabel.setObjectName("nbRevisionsLabel")
        self.horizontalLayout.addWidget(self.nbRevisionsLabel)
        self.nbRevBox = QtWidgets.QSpinBox(self.tab_3)
        self.nbRevBox.setProperty("value", 10)
        self.nbRevBox.setObjectName("nbRevBox")
        self.horizontalLayout.addWidget(self.nbRevBox)
        self.loadHistoryButton = QtWidgets.QPushButton(self.tab_3)
        self.loadHistoryButton.setObjectName("loadHistoryButton")
        self.horizontalLayout.addWidget(self.loadHistoryButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.descriptionEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.descriptionEdit.setText("")
        self.descriptionEdit.setObjectName("descriptionEdit")
        self.horizontalLayout_3.addWidget(self.descriptionEdit)
        self.minorBox = QtWidgets.QCheckBox(self.centralwidget)
        self.minorBox.setObjectName("minorBox")
        self.horizontalLayout_3.addWidget(self.minorBox)
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setEnabled(False)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout_3.addWidget(self.saveButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 608, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionBackends = QtWidgets.QAction(MainWindow)
        self.actionBackends.setObjectName("actionBackends")
        self.menuFile.addAction(self.actionBackends)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.toolBar.addAction(self.actionBackends)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.actionExit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "QWebcontentedit"))
        self.loadButton.setText(_translate("MainWindow", "Load"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Edit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Preview"))
        item = self.historyTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.historyTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Time"))
        item = self.historyTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Author"))
        item = self.historyTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Summary"))
        self.nbRevisionsLabel.setText(_translate("MainWindow", "Number of revisions"))
        self.loadHistoryButton.setText(_translate("MainWindow", "Reload"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "History"))
        self.minorBox.setText(_translate("MainWindow", "Minor edit"))
        self.saveButton.setText(_translate("MainWindow", "No changes"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionBackends.setText(_translate("MainWindow", "Backends"))
