# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'minimovie.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MiniMovie(object):
    def setupUi(self, MiniMovie):
        MiniMovie.setObjectName("MiniMovie")
        MiniMovie.resize(563, 138)
        MiniMovie.setFrameShape(QtWidgets.QFrame.StyledPanel)
        MiniMovie.setFrameShadow(QtWidgets.QFrame.Raised)
        self.horizontalLayout = QtWidgets.QHBoxLayout(MiniMovie)
        self.horizontalLayout.setContentsMargins(9, 5, -1, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.imageLabel = QtWidgets.QLabel(MiniMovie)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageLabel.sizePolicy().hasHeightForWidth())
        self.imageLabel.setSizePolicy(sizePolicy)
        self.imageLabel.setText("")
        self.imageLabel.setObjectName("imageLabel")
        self.horizontalLayout.addWidget(self.imageLabel)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(MiniMovie)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(MiniMovie)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 0, 1, 1)
        self.titleLabel = QtWidgets.QLabel(MiniMovie)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleLabel.sizePolicy().hasHeightForWidth())
        self.titleLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.titleLabel.setFont(font)
        self.titleLabel.setWordWrap(True)
        self.titleLabel.setObjectName("titleLabel")
        self.gridLayout.addWidget(self.titleLabel, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(MiniMovie)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.shortDescLabel = QtWidgets.QLabel(MiniMovie)
        self.shortDescLabel.setWordWrap(False)
        self.shortDescLabel.setObjectName("shortDescLabel")
        self.gridLayout.addWidget(self.shortDescLabel, 1, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.viewButton = QtWidgets.QPushButton(MiniMovie)
        self.viewButton.setMaximumSize(QtCore.QSize(120, 20))
        self.viewButton.setObjectName("viewButton")
        self.horizontalLayout_2.addWidget(self.viewButton)
        self.newTabButton = QtWidgets.QPushButton(MiniMovie)
        self.newTabButton.setMaximumSize(QtCore.QSize(120, 20))
        self.newTabButton.setObjectName("newTabButton")
        self.horizontalLayout_2.addWidget(self.newTabButton)
        self.viewThumbnailButton = QtWidgets.QPushButton(MiniMovie)
        self.viewThumbnailButton.setMaximumSize(QtCore.QSize(120, 20))
        self.viewThumbnailButton.setObjectName("viewThumbnailButton")
        self.horizontalLayout_2.addWidget(self.viewThumbnailButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.backendButton = QtWidgets.QPushButton(MiniMovie)
        self.backendButton.setMaximumSize(QtCore.QSize(16777215, 20))
        self.backendButton.setFlat(True)
        self.backendButton.setObjectName("backendButton")
        self.horizontalLayout_3.addWidget(self.backendButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)

        self.retranslateUi(MiniMovie)
        QtCore.QMetaObject.connectSlotsByName(MiniMovie)

    def retranslateUi(self, MiniMovie):
        _translate = QtCore.QCoreApplication.translate
        MiniMovie.setWindowTitle(_translate("MiniMovie", "Form"))
        self.label_5.setText(_translate("MiniMovie", "Title"))
        self.label_8.setText(_translate("MiniMovie", "Short description:"))
        self.titleLabel.setText(_translate("MiniMovie", "TextLabel"))
        self.label.setText(_translate("MiniMovie", "Where"))
        self.shortDescLabel.setText(_translate("MiniMovie", "TextLabel"))
        self.viewButton.setText(_translate("MiniMovie", "View"))
        self.newTabButton.setText(_translate("MiniMovie", "View in new tab"))
        self.viewThumbnailButton.setText(_translate("MiniMovie", "View thumbnail"))
        self.backendButton.setText(_translate("MiniMovie", "PushButton"))
