# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'minisubtitle.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MiniSubtitle(object):
    def setupUi(self, MiniSubtitle):
        MiniSubtitle.setObjectName("MiniSubtitle")
        MiniSubtitle.resize(464, 136)
        MiniSubtitle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        MiniSubtitle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.horizontalLayout = QtWidgets.QHBoxLayout(MiniSubtitle)
        self.horizontalLayout.setContentsMargins(9, 5, -1, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.imageLabel = QtWidgets.QLabel(MiniSubtitle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageLabel.sizePolicy().hasHeightForWidth())
        self.imageLabel.setSizePolicy(sizePolicy)
        self.imageLabel.setText("")
        self.imageLabel.setObjectName("imageLabel")
        self.horizontalLayout.addWidget(self.imageLabel)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label_5 = QtWidgets.QLabel(MiniSubtitle)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.nameLabel = QtWidgets.QLabel(MiniSubtitle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nameLabel.sizePolicy().hasHeightForWidth())
        self.nameLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.nameLabel.setFont(font)
        self.nameLabel.setWordWrap(True)
        self.nameLabel.setObjectName("nameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nameLabel)
        self.label_8 = QtWidgets.QLabel(MiniSubtitle)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.nbcdLabel = QtWidgets.QLabel(MiniSubtitle)
        self.nbcdLabel.setObjectName("nbcdLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.nbcdLabel)
        self.label = QtWidgets.QLabel(MiniSubtitle)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label)
        self.newTabButton = QtWidgets.QPushButton(MiniSubtitle)
        self.newTabButton.setMaximumSize(QtCore.QSize(16777215, 20))
        self.newTabButton.setObjectName("newTabButton")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.newTabButton)
        self.viewButton = QtWidgets.QPushButton(MiniSubtitle)
        self.viewButton.setMaximumSize(QtCore.QSize(16777215, 20))
        self.viewButton.setObjectName("viewButton")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.viewButton)
        self.backendButton = QtWidgets.QPushButton(MiniSubtitle)
        self.backendButton.setMaximumSize(QtCore.QSize(16777215, 20))
        self.backendButton.setFlat(True)
        self.backendButton.setObjectName("backendButton")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.backendButton)
        self.horizontalLayout.addLayout(self.formLayout)

        self.retranslateUi(MiniSubtitle)
        QtCore.QMetaObject.connectSlotsByName(MiniSubtitle)

    def retranslateUi(self, MiniSubtitle):
        _translate = QtCore.QCoreApplication.translate
        MiniSubtitle.setWindowTitle(_translate("MiniSubtitle", "Form"))
        self.label_5.setText(_translate("MiniSubtitle", "Name"))
        self.nameLabel.setText(_translate("MiniSubtitle", "TextLabel"))
        self.label_8.setText(_translate("MiniSubtitle", "Nb CD"))
        self.nbcdLabel.setText(_translate("MiniSubtitle", "TextLabel"))
        self.label.setText(_translate("MiniSubtitle", "Where"))
        self.newTabButton.setText(_translate("MiniSubtitle", "View in new tab"))
        self.viewButton.setText(_translate("MiniSubtitle", "View"))
        self.backendButton.setText(_translate("MiniSubtitle", "PushButton"))
