# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'person.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Person(object):
    def setupUi(self, Person):
        Person.setObjectName("Person")
        Person.resize(857, 629)
        Person.setFrameShape(QtWidgets.QFrame.StyledPanel)
        Person.setFrameShadow(QtWidgets.QFrame.Raised)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(Person)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_3 = QtWidgets.QFrame(Person)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.imageLabel = QtWidgets.QLabel(self.frame_3)
        self.imageLabel.setText("")
        self.imageLabel.setObjectName("imageLabel")
        self.verticalLayout_2.addWidget(self.imageLabel)
        self.frame_12 = QtWidgets.QFrame(self.frame_3)
        self.frame_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.filmographyButton = QtWidgets.QPushButton(self.frame_12)
        self.filmographyButton.setObjectName("filmographyButton")
        self.horizontalLayout_4.addWidget(self.filmographyButton)
        self.label_2 = QtWidgets.QLabel(self.frame_12)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.filmographyCombo = QtWidgets.QComboBox(self.frame_12)
        self.filmographyCombo.setObjectName("filmographyCombo")
        self.filmographyCombo.addItem("")
        self.horizontalLayout_4.addWidget(self.filmographyCombo)
        self.verticalLayout_2.addWidget(self.frame_12)
        self.frame_15 = QtWidgets.QFrame(self.frame_3)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.moviesInCommonButton = QtWidgets.QPushButton(self.frame_15)
        self.moviesInCommonButton.setObjectName("moviesInCommonButton")
        self.verticalLayout_4.addWidget(self.moviesInCommonButton)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_12 = QtWidgets.QLabel(self.frame_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_15.addWidget(self.label_12)
        self.moviesInCommonEdit = QtWidgets.QLineEdit(self.frame_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.moviesInCommonEdit.sizePolicy().hasHeightForWidth())
        self.moviesInCommonEdit.setSizePolicy(sizePolicy)
        self.moviesInCommonEdit.setObjectName("moviesInCommonEdit")
        self.horizontalLayout_15.addWidget(self.moviesInCommonEdit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_15)
        self.verticalLayout_2.addWidget(self.frame_15)
        self.horizontalLayout_3.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(Person)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.idFrame = QtWidgets.QFrame(self.frame_4)
        self.idFrame.setMaximumSize(QtCore.QSize(16777215, 40))
        self.idFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.idFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.idFrame.setObjectName("idFrame")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.idFrame)
        self.horizontalLayout_13.setContentsMargins(-1, 3, -1, 3)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_11 = QtWidgets.QLabel(self.idFrame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_13.addWidget(self.label_11)
        self.idEdit = QtWidgets.QLineEdit(self.idFrame)
        self.idEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.idEdit.setReadOnly(True)
        self.idEdit.setObjectName("idEdit")
        self.horizontalLayout_13.addWidget(self.idEdit)
        self.verticalLayout.addWidget(self.idFrame)
        self.frame = QtWidgets.QFrame(self.frame_4)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.nameLabel = QtWidgets.QLabel(self.frame)
        self.nameLabel.setText("")
        self.nameLabel.setObjectName("nameLabel")
        self.horizontalLayout.addWidget(self.nameLabel)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.frame_4)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.birthDateLabel = QtWidgets.QLabel(self.frame_2)
        self.birthDateLabel.setText("")
        self.birthDateLabel.setObjectName("birthDateLabel")
        self.horizontalLayout_2.addWidget(self.birthDateLabel)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_8 = QtWidgets.QFrame(self.frame_4)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.realNameLabel = QtWidgets.QLabel(self.frame_8)
        self.realNameLabel.setText("")
        self.realNameLabel.setObjectName("realNameLabel")
        self.horizontalLayout_7.addWidget(self.realNameLabel)
        self.verticalLayout.addWidget(self.frame_8)
        self.frame_11 = QtWidgets.QFrame(self.frame_4)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_10 = QtWidgets.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.birthPlaceLabel = QtWidgets.QLabel(self.frame_11)
        self.birthPlaceLabel.setText("")
        self.birthPlaceLabel.setObjectName("birthPlaceLabel")
        self.horizontalLayout_10.addWidget(self.birthPlaceLabel)
        self.verticalLayout.addWidget(self.frame_11)
        self.frame_10 = QtWidgets.QFrame(self.frame_4)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_9 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.deathDateLabel = QtWidgets.QLabel(self.frame_10)
        self.deathDateLabel.setText("")
        self.deathDateLabel.setObjectName("deathDateLabel")
        self.horizontalLayout_9.addWidget(self.deathDateLabel)
        self.verticalLayout.addWidget(self.frame_10)
        self.frame_9 = QtWidgets.QFrame(self.frame_4)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_5 = QtWidgets.QFrame(self.frame_9)
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.biographyLabel = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.biographyLabel.setFont(font)
        self.biographyLabel.setObjectName("biographyLabel")
        self.verticalLayout_3.addWidget(self.biographyLabel)
        self.biographyButton = QtWidgets.QPushButton(self.frame_5)
        self.biographyButton.setObjectName("biographyButton")
        self.verticalLayout_3.addWidget(self.biographyButton)
        self.horizontalLayout_8.addWidget(self.frame_5)
        self.shortBioPlain = QtWidgets.QPlainTextEdit(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shortBioPlain.sizePolicy().hasHeightForWidth())
        self.shortBioPlain.setSizePolicy(sizePolicy)
        self.shortBioPlain.setMaximumSize(QtCore.QSize(16777215, 250))
        self.shortBioPlain.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.shortBioPlain.setObjectName("shortBioPlain")
        self.horizontalLayout_8.addWidget(self.shortBioPlain)
        self.verticalLayout.addWidget(self.frame_9)
        self.horizontalLayout_3.addWidget(self.frame_4)

        self.retranslateUi(Person)
        QtCore.QMetaObject.connectSlotsByName(Person)

    def retranslateUi(self, Person):
        _translate = QtCore.QCoreApplication.translate
        Person.setWindowTitle(_translate("Person", "Frame"))
        self.filmographyButton.setText(_translate("Person", "view\n"
"filmography"))
        self.label_2.setText(_translate("Person", "as"))
        self.filmographyCombo.setItemText(0, _translate("Person", "all"))
        self.moviesInCommonButton.setText(_translate("Person", "Search movies in common with"))
        self.label_12.setText(_translate("Person", "Person ID :"))
        self.label_11.setText(_translate("Person", "Id:"))
        self.label.setText(_translate("Person", "name:"))
        self.label_3.setText(_translate("Person", "Birth date:"))
        self.label_7.setText(_translate("Person", "Real Name:"))
        self.label_10.setText(_translate("Person", "Birth place:"))
        self.label_9.setText(_translate("Person", "Death date:"))
        self.biographyLabel.setText(_translate("Person", "Short biography:"))
        self.biographyButton.setText(_translate("Person", "view full\n"
"biography"))
