[tool.poetry]
name = "openapispecdiff"
version = "0.1.0"
description = "Difference between two OpenAPISpec files"
authors = ["Bala <balak@cloudvector.com>"]

[tool.poetry.dependencies]
python = "^3.5"

[tool.poetry.dev-dependencies]
pex = "*"

[tool.poetry.scripts]
openapidiff = 'OpenApiSpecDiff.OpenApiSpecDiff:main'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
