[tool.poetry]
name = "django-dramatiq-pg"
version = "1.0.2"
description = "Integration of Django with dramatiq-pg"
readme = "README.rst"
authors = ["Curtis Maloney <curtis@tinbrain.net>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
django = ">= 2.2"
dramatiq-pg = ">= 0.7.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
