# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'details.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(523, 444)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.titleEdit = QtWidgets.QLineEdit(self.widget)
        self.titleEdit.setReadOnly(True)
        self.titleEdit.setObjectName("titleEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.titleEdit)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.authorEdit = QtWidgets.QLineEdit(self.widget)
        self.authorEdit.setReadOnly(True)
        self.authorEdit.setObjectName("authorEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.authorEdit)
        self.creationEdit = QtWidgets.QLineEdit(self.widget)
        self.creationEdit.setReadOnly(True)
        self.creationEdit.setObjectName("creationEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.creationEdit)
        self.assigneeEdit = QtWidgets.QLineEdit(self.widget)
        self.assigneeEdit.setReadOnly(True)
        self.assigneeEdit.setObjectName("assigneeEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.assigneeEdit)
        self.lastEdit = QtWidgets.QLineEdit(self.widget)
        self.lastEdit.setReadOnly(True)
        self.lastEdit.setObjectName("lastEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lastEdit)
        self.linkLabel = QtWidgets.QLabel(self.widget)
        self.linkLabel.setOpenExternalLinks(True)
        self.linkLabel.setObjectName("linkLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.linkLabel)
        self.verticalLayout.addWidget(self.widget)
        self.splitter = QtWidgets.QSplitter(Dialog)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.bodyEdit = QtWidgets.QPlainTextEdit(self.splitter)
        self.bodyEdit.setReadOnly(True)
        self.bodyEdit.setObjectName("bodyEdit")
        self.updatesEdit = QtWidgets.QTextEdit(self.splitter)
        self.updatesEdit.setReadOnly(True)
        self.updatesEdit.setObjectName("updatesEdit")
        self.verticalLayout.addWidget(self.splitter)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "View issue"))
        self.label.setText(_translate("Dialog", "Author"))
        self.label_2.setText(_translate("Dialog", "Assignee"))
        self.label_3.setText(_translate("Dialog", "Creation date"))
        self.label_4.setText(_translate("Dialog", "Last update"))
        self.label_5.setText(_translate("Dialog", "Title"))
        self.linkLabel.setText(_translate("Dialog", "View page"))
