[tool.poetry]
name = "django-sidebar-menu"
version = "0.1.0"
description = "Create sidebar menu easily"
authors = ["Cleiton Lima <cleiton.limapin@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/CleitonDeLima/django-easy-tenants"
homepage = "https://github.com/CleitonDeLima/django-easy-tenants"
classifiers = [
    'Environment :: Web Environment',
    'Framework :: Django',
    'Intended Audience :: Developers',
    'License :: OSI Approved :: MIT License',
    'Operating System :: OS Independent',
    'Programming Language :: Python',
    'Programming Language :: Python :: 3',
    'Topic :: Internet :: WWW/HTTP :: Dynamic Content',
]
packages = [
    {include = "sidebar_menu"}
]

[tool.poetry.dependencies]
python = ">=3.7"
django = ">=2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-django = "^3.8.0"
pytest-cov = "^2.8.1"
tox = "^3.14.6"
black = "^19.10b0"

[tool.black]
line-length = 80

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
