
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "ea334c216e8f30c38c0db84576d2fbb6d188f710",
 "version": "1.14.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
