
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2020-03-23T19:33:43+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "43b9f617eafbde59ecd7342d23f5c4d96a0354d0",
 "version": "0.7.22"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
