# https://git.ligo.org/lscsoft/example-ci-project/wikis/automatically-produce-documentation
# https://wiki.ligo.org/viewauth/DASWG/GitLigoOrg#Accessing_GitLab_Pages

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"

cache:
  paths:
    - .cache/

stages:
  - test
  - deploy

.template:test:unit: &template-test-unit
  script:
    - python --version
    - apt update -qy
    - apt install --assume-yes python-pip
    - pip install .
    - make test-unit

.template:test:integration: &template-test-integration
  script:
    - python --version
    - apt update -qy
    - apt install --assume-yes python-pip
    - pip install .
    - make test-integration

.template:test:validation: &template-test-validation
  only:
    variables:
      - $LISO_GIT_ARCHIVE_ACCESS_TOKEN
      - $LISO_GIT_ARCHIVE_URL
  script:
    - mkdir liso
    - cd liso
    - wget -O liso.tar.gz ${LISO_GIT_ARCHIVE_URL}
    - tar -xvf liso.tar.gz -C . --wildcards liso-linux*/ --strip-components=1
    - chmod +x fil_static
    - cd ..
    - export LISO_DIR=$(pwd)/liso
    - export LISO_PATH=$LISO_DIR/fil_static
    - python --version
    - apt update -qy
    - apt install --assume-yes python-pip
    - pip install .
    - make test-validation

test unit:latest:
  image: python:latest
  stage: test
  <<: *template-test-unit

test unit:3.6:
  image: python:3.6
  stage: test
  <<: *template-test-unit

test unit:3.7:
  image: python:3.7
  stage: test
  <<: *template-test-unit

test integration:latest:
  image: python:latest
  stage: test
  <<: *template-test-integration

test integration:3.6:
  image: python:3.6
  stage: test
  <<: *template-test-integration

test integration:3.7:
  image: python:3.7
  stage: test
  <<: *template-test-integration

test validation:latest:
  image: python:latest
  stage: test
  <<: *template-test-validation

test validation:3.6:
  image: python:3.6
  stage: test
  <<: *template-test-validation

test validation:3.7:
  image: python:3.7
  stage: test
  <<: *template-test-validation

# Generate the documentation only on creation of new tags.
pages:
  image: python:3.8
  stage: deploy
  only:
    refs:
      - tags
    variables:
      - $LISO_GIT_ARCHIVE_ACCESS_TOKEN
      - $LISO_GIT_ARCHIVE_URL
  script:
    - mkdir liso
    - cd liso
    - wget -O liso.tar.gz ${LISO_GIT_ARCHIVE_URL}
    - tar -xvf liso.tar.gz -C . --wildcards liso-linux*/ --strip-components=1
    - chmod +x fil_static
    - cd ..
    - export LISO_DIR=$(pwd)/liso
    - export LISO_PATH=$LISO_DIR/fil_static
    - python --version
    - apt update -qy
    - apt install --assume-yes python-pip
    - pip install .[dev]
    - cd docs
    - make html
    - mv _build/html ../public
  artifacts:
    paths:
    - public

# Generate PyPI release only on creation of new tags.
pypi:
  image: python:3.8
  stage: deploy
  only:
    refs:
      - tags
    variables:
      - $TWINE_USERNAME
      - $TWINE_PASSWORD
  script:
    - python --version
    - apt update -qy
    - apt install --assume-yes python-pip
    - pip install twine
    - python setup.py sdist bdist_wheel
    - python -m twine upload dist/zero-*
