[tool.poetry]
name = "jupyter_ascending"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.6"
watchdog = "^0.10.2"
jupytext = "^1.3.4"
jsonrpcserver = {extras = ["requests"], version = "^4.1.2"}
jsonrpcclient = {extras = ["requests"], version = "^3.3.5"}
ipywidgets = "^7.5.1"
loguru = "^0.4.1"
tornado = "^6.0.4"
attrs = "^19.3.0"

[tool.poetry.dev-dependencies]
python-language-server = {extras = ["all"], version = "^0.31.9"}
black = "^19.10b0"
pyfixfmt = "^0.9.0"

[tool.poetry.scripts]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"


