[tool.poetry]
name = "mygp-cli"
version = "0.0.7dev1"
description = "Command-line interface for the Marketplace Sandbox API"
authors = ["Igor Brejc <igor.brejc@nfcsb.com>"]
include = ["docs/mygp-cli how to use.md"]

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.23.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
mypy = "^0.770"
pylint = "^2.4.4"

[tool.poetry.scripts]
mygp-cli = "mygp_cli.main:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
