language: python
python:
- 3.5
- 3.6
- 3.7
- 3.8
- pypy3
install:
- pip install tox-travis
script:
- tox
before_install:
- pip install codecov
after_success:
- tox -e coverage
- codecov
notifications:
  email: false
