################################################################################
################################################################################
###
###  This file is automatically generated. Do not change this file! Changes
###  will get overwritten! Change the source file for "setup.py" instead.
###  This is either 'packageinfo.json' or 'packageinfo.jsonc'
###
################################################################################
################################################################################


from setuptools import setup

def readme():
	with open("README.md", "r", encoding="UTF-8-sig") as f:
		return f.read()

setup(
	author = "Jürgen Knauth",
	author_email = "pubsrc@binary-overflow.de",
	classifiers = [
		"Development Status :: 4 - Beta",
		"Environment :: Console",
		"License :: OSI Approved :: Apache Software License",
	],
	description = "This python module provides a variety of essential functions for implementing versatile programs using the console. (Please have a look at the documentation for details.)",
	download_url = "https://github.com/jkpubsrc/python-module-jk-htmlparser/tarball/0.2020.3.20",
	include_package_data = False,
	install_requires = [
	],
	keywords = [
		"console",
		"terminal",
		"colors",
		"stdin",
	],
	license = "Apache 2.0",
	name = "jk_console",
	packages = [
		"jk_console",
		"jk_console.viewport",
		"jk_console.demo",
	],
	url = "https://github.com/jkpubsrc/python-module-jk-htmlparser",
	version = "0.2020.3.20",
	zip_safe = False,
	long_description = readme(),
	long_description_content_type="text/markdown",
)
