# coding: utf-8

"""
    ARLAS Exploration API

    Explore the content of ARLAS collections

    OpenAPI spec version: 12.0.7
    Contact: contact@gisaia.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import arlas_api_python
from arlas_api_python.rest import ApiException
from arlas_api_python.models.aggregated_geometry import AggregatedGeometry


class TestAggregatedGeometry(unittest.TestCase):
    """ AggregatedGeometry unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAggregatedGeometry(self):
        """
        Test AggregatedGeometry
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = arlas_api_python.models.aggregated_geometry.AggregatedGeometry()
        pass


if __name__ == '__main__':
    unittest.main()
