# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'backendcfg.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BackendCfg(object):
    def setupUi(self, BackendCfg):
        BackendCfg.setObjectName("BackendCfg")
        BackendCfg.resize(622, 516)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(BackendCfg)
        self.verticalLayout_3.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_3 = QtWidgets.QFrame(BackendCfg)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.updateButton = QtWidgets.QPushButton(self.frame_3)
        self.updateButton.setObjectName("updateButton")
        self.horizontalLayout_3.addWidget(self.updateButton)
        self.repositoriesButton = QtWidgets.QPushButton(self.frame_3)
        self.repositoriesButton.setObjectName("repositoriesButton")
        self.horizontalLayout_3.addWidget(self.repositoriesButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_3.addWidget(self.frame_3)
        self.splitter_2 = QtWidgets.QSplitter(BackendCfg)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.splitter_2)
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.backendsList = QtWidgets.QTreeWidget(self.horizontalLayoutWidget)
        self.backendsList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.backendsList.setIconSize(QtCore.QSize(24, 24))
        self.backendsList.setRootIsDecorated(False)
        self.backendsList.setUniformRowHeights(False)
        self.backendsList.setItemsExpandable(False)
        self.backendsList.setAnimated(True)
        self.backendsList.setWordWrap(False)
        self.backendsList.setExpandsOnDoubleClick(False)
        self.backendsList.setObjectName("backendsList")
        self.backendsList.header().setCascadingSectionResizes(False)
        self.backendsList.header().setHighlightSections(True)
        self.horizontalLayout.addWidget(self.backendsList)
        self.frame = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.addButton = QtWidgets.QPushButton(self.frame)
        self.addButton.setObjectName("addButton")
        self.verticalLayout.addWidget(self.addButton)
        self.removeButton = QtWidgets.QPushButton(self.frame)
        self.removeButton.setObjectName("removeButton")
        self.verticalLayout.addWidget(self.removeButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout.addWidget(self.frame)
        self.configFrame = QtWidgets.QFrame(self.splitter_2)
        self.configFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.configFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.configFrame.setObjectName("configFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.configFrame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.configFrame)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.modulesList = QtWidgets.QListWidget(self.configFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modulesList.sizePolicy().hasHeightForWidth())
        self.modulesList.setSizePolicy(sizePolicy)
        self.modulesList.setIconSize(QtCore.QSize(24, 24))
        self.modulesList.setObjectName("modulesList")
        self.verticalLayout_2.addWidget(self.modulesList)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.frame_2 = QtWidgets.QFrame(self.configFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.moduleInfo = QtWidgets.QTextEdit(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.moduleInfo.sizePolicy().hasHeightForWidth())
        self.moduleInfo.setSizePolicy(sizePolicy)
        self.moduleInfo.setReadOnly(True)
        self.moduleInfo.setObjectName("moduleInfo")
        self.verticalLayout_4.addWidget(self.moduleInfo)
        self.configLayout = QtWidgets.QFormLayout()
        self.configLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.configLayout.setObjectName("configLayout")
        self.nameEdit = QtWidgets.QLineEdit(self.frame_2)
        self.nameEdit.setObjectName("nameEdit")
        self.configLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nameEdit)
        self.proxyBox = QtWidgets.QCheckBox(self.frame_2)
        self.proxyBox.setObjectName("proxyBox")
        self.configLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.proxyBox)
        self.proxyEdit = QtWidgets.QLineEdit(self.frame_2)
        self.proxyEdit.setEnabled(False)
        self.proxyEdit.setObjectName("proxyEdit")
        self.configLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.proxyEdit)
        self.registerButton = QtWidgets.QPushButton(self.frame_2)
        self.registerButton.setObjectName("registerButton")
        self.configLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.registerButton)
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setObjectName("label")
        self.configLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.verticalLayout_4.addLayout(self.configLayout)
        self.configButtonBox = QtWidgets.QDialogButtonBox(self.frame_2)
        self.configButtonBox.setOrientation(QtCore.Qt.Horizontal)
        self.configButtonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.configButtonBox.setObjectName("configButtonBox")
        self.verticalLayout_4.addWidget(self.configButtonBox)
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.verticalLayout_3.addWidget(self.splitter_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(BackendCfg)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox)

        self.retranslateUi(BackendCfg)
        self.buttonBox.clicked['QAbstractButton*'].connect(BackendCfg.accept)
        QtCore.QMetaObject.connectSlotsByName(BackendCfg)
        BackendCfg.setTabOrder(self.backendsList, self.addButton)
        BackendCfg.setTabOrder(self.addButton, self.removeButton)
        BackendCfg.setTabOrder(self.removeButton, self.modulesList)
        BackendCfg.setTabOrder(self.modulesList, self.moduleInfo)
        BackendCfg.setTabOrder(self.moduleInfo, self.nameEdit)
        BackendCfg.setTabOrder(self.nameEdit, self.proxyBox)
        BackendCfg.setTabOrder(self.proxyBox, self.proxyEdit)
        BackendCfg.setTabOrder(self.proxyEdit, self.registerButton)
        BackendCfg.setTabOrder(self.registerButton, self.configButtonBox)
        BackendCfg.setTabOrder(self.configButtonBox, self.buttonBox)

    def retranslateUi(self, BackendCfg):
        _translate = QtCore.QCoreApplication.translate
        BackendCfg.setWindowTitle(_translate("BackendCfg", "Backends configuration"))
        self.updateButton.setText(_translate("BackendCfg", "Update modules"))
        self.repositoriesButton.setText(_translate("BackendCfg", "Repositories"))
        self.backendsList.setSortingEnabled(True)
        self.backendsList.headerItem().setText(0, _translate("BackendCfg", "Name"))
        self.backendsList.headerItem().setText(1, _translate("BackendCfg", "Module"))
        self.addButton.setText(_translate("BackendCfg", "Add"))
        self.removeButton.setText(_translate("BackendCfg", "Remove"))
        self.label_2.setText(_translate("BackendCfg", "Available modules:"))
        self.modulesList.setSortingEnabled(True)
        self.proxyBox.setText(_translate("BackendCfg", "Proxy:"))
        self.registerButton.setText(_translate("BackendCfg", "Register an account..."))
        self.label.setText(_translate("BackendCfg", "Name:"))
