[tool.poetry]
name = "globus-action-provider-tools"
version = "0.7"
description = "Tools to help developers build services that implement the Action Provider specification."
authors = [
    "Jim Pruyne <pruyne@globus.org>",
]
keywords = [
  "globus",
  "automation",
  "workflow",
  "action_provider"
  ]
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "License :: Free To Use But Restricted",
  "Programming Language :: Python :: 3.6",
  "Programming Language :: Python :: 3.7",
  "Topic :: Internet :: WWW/HTTP",
  "Topic :: Software Development :: Libraries :: Application Frameworks",
  "Topic :: Software Development :: Libraries :: Python Modules"
  ]

readme = "README.rst"

[tool.poetry.dependencies]
python = "^3.6"
"dogpile.cache"="^0.7.1"
globus-sdk="^1.7.1"
globus-nexus-client="^0.2.8"
openapi-core="^0.11.0"

[tool.poetry.dev-dependencies]
python-language-server = "^0.31.8"
pyls-black = "^0.4.4"
pyls-isort = "^0.1.1"
pyls-mypy = "^0.1.8"
flake8 = "^3.7"
flake8-bugbear = "^18.8"
importmagic = "^0.1.7"
epc = "^0.0.5"
pytest = "^5.0"
werkzeug = "^0.15.4"
flask = "^1.1.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
