[tool.poetry]
name = "dotstrings"
version = "1.0.2"
description = "Tools for dealing with the .strings files for iOS and macOS"

license = "MIT"

authors = [
    "Dale Myers <dalemy@microsoft.com>"
]

readme = 'README.md'

repository = "https://github.com/Microsoft/dotstrings"
homepage = "https://github.com/Microsoft/dotstrings"

keywords = ['localization', 'iOS', 'macOS', 'strings']

classifiers = [
    'Development Status :: 5 - Production/Stable',
    'Environment :: Console',
    'Environment :: MacOS X',
    'Intended Audience :: Developers',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.6',
    'Programming Language :: Python :: 3.7',
    'Topic :: Software Development',
    'Topic :: Utilities'
]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
black = "=19.3b0"
mypy = "=0.670"
pylint = "=2.3.1"
pytest = "=4.0.1"
pytest-cov = "=2.6.0"


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
