[tool.poetry]
name = "jiradata"
version = "0.4.0"
description = "Simple JIRA data manipulation"
authors = ["Khalid <khalidck@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
autopep8 = "^1.5"
pylint = "^2.4.4"
isort = "^4.3.21"
mypy = "^0.770"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
