[tool.poetry]
name = "ccautil"
version = "0.1.0"
description = "a set of utilities"
authors = ["Chris Allison <chris.charles.allison+ccautil@gmail.com>"]
license = "GPL-3.0-or-later"
readme = "README.md"
repository = "https://github.com/ccdale/ccautil"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
