[tool.poetry]
name = "bagitfs"
version = "0.1.0"
description = "Bagit package"
authors = ["Radim Spigel <spigel@cesnet.cz>"]

[tool.poetry.dependencies]
python = "^3.6"
bagit = "1.7.0"
fs = "2.2.1"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12", "bagit", "fs"]
build-backend = "poetry.masonry.api"
