# This file was automatically generated by sub\epyqlib\epyqlib\cli\generateversion.py
__version_build_time__ = '2020-03-20T12:48:45.492083'

__version__ = '2020.3.7'
__sha__ = '1b047649d2279ffec5358e67868c06c50c6fd72f'
__revision__ = '1b047649d2279ffec5358e67868c06c50c6fd72f'
