[tool.poetry]
name = "pynet_annek"
version = "0.5.4"
description = "A cli for managing network switches"
authors = ["Michael MacKenna <mpmackenna@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
netmiko = "^2.4"
termcolor = "^1.1"
click = "^7.0"

[tool.poetry.dev-dependencies]
pylint = "^2.4"
autopep8 = "^1.4"
wheel = "^0.33.6"
keyring = "^21.1.0"
black = "^19.10b0"
mdv = "^1.7.4"

[tool.poetry.scripts]
pynet = 'pynet_annek.cli:main'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
