[tool.poetry]
name = "mealprep"
version = "1.0.15"
description = "Python package that ease the pain in pre-processing like outlier finding, numerical/categorical data and etc."
authors = ["luhuayue <luhuayueapp@163.com>"]
license = "MIT"

readme = "README.md"
homepage = "https://github.com/UBC-MDS/mealprep"
repository = "https://github.com/UBC-MDS/mealprep"
documentation = 'https://mealprep.readthedocs.io'

[tool.poetry.dependencies]
python = "^3.6.1"
pandas = "^1.0.1"
vega_datasets = "^0.8.0"
sklearn = "^0.0"
flake8 = "^3.7.9"
codecov = "^2.0.16"
python-semantic-release = "^4.10.0"
sphinxcontrib-napoleon = "^0.7"

[tool.poetry.dev-dependencies]
pytest = "^5.3.5"
pytest-cov = "^2.8.1"
sphinx = "^2.4.4"
sphinxcontrib-napoleon = "^0.7"
vega_datasets = "^0.8.0"

[tool.semantic_release]
version_variable = "mealprep/__init__.py:__version__"
version_source = "commit"
upload_to_pypi = "false"
patch_without_tag = "true"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
