[tool.poetry]
name = "computlib"
version = "0.1.0"
description = "Simple mathematical library"
authors = ["Mathieu LYSAKOWSKI <mathieu@phec.net>"]
maintainers = ["Mathieu LYSAKOWSKI <mathieu@phec.net>"]
license = "GPL-3.0"
readme = "README.md"
repository = "https://gitlab.com/mlysakowski/computlib"
documentation = "https://gitlab.com/mlysakowski/computlib"
keywords = ["Computlib"]

include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^4.1"
pytest-cov = "^2.8.1"
pytest-sugar = "^0.9.2"
mkdocs = "^1.1"
markdown-include = "^0.5.1"
tox = "^3.14.5"
pygments = "^2.6.1"
black = "^19.10b0"
auto-changelog = "^0.4.0"
bandit = "^1.6.2"
safety = "^1.8.7"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.urls]
issues = "https://gitlab.com/mlysakowski/computlib/-/issues"
