dist: xenial
sudo: required
language: python
stages:
- name: deploy
  if: branch = master
jobs:
  include:
  - stage: test
    python: 3.7
    install: pip install tox-travis
    script: tox
  - stage: deploy
    python: 3.7
    install: skip
    script: skip
    if: NOT type = pull_request
    deploy:
      provider: pypi
      distributions: sdist bdist_wheel
      user: sciris
      password:
        secure: hDzhg+/SQrIPo/3F55yLhljIbUickIpfDwx5pkQC0Q/gFrOh6MPqKKJkI+0HUio5REAOosN+4cn54zFuIY6jl1a+yzXpV0sb+TiMCJvScowSbCACZK7fa8hSlQLQ3FQzCNDVyXc2CDUQyaBlNWD1U2U1yPt9s8h1vX5WQ5kdJS1dO8Bbi2yEjyB++4zxXBKUSmcb9XYPDe/Eiq979ctg6A/t8E+p64vcL6EiZ9l782FOYsynKRpJYEG9XqHYxhiAu9z5oNfEY2o5iaSNPQ5mFqAtLA6QEIQP7g2ogbHEAg+Mgd3zn6FnUiCfbBwc066fwaifda3AGqWmCa+Po3Lc0ON/kL7LJnm7DFpRxbA02C/vSpYaDGiw5DoEXAqmPeuT6cF7dn915bpkAltjWgEiUW+T9yh7GSXZKlCFdPB8OdZEN3+fD2zp+NcaXG/qO0Gjv4xed4X3IbysiISO1ICb1pVKh/rnoPvMBacQeEQqY7y06mlc5rtUhEpzN4o3A+FoqLicRxc9H7EV8dzKHCl3XHz+Mp5c+++x4iHT0z66Da1TmOsAqDGpkunbWej/RUDlnlmXKMRP0Uiuoly1YyxnInz4Nd7spsGfw4vJO9xt8nHFd5L1o2gfTbydHBkjTYhpIVqqFrNgcqVvAqg+hhV4e2zLsfyZbUILq48MaDF8AHI=
    on:
      repo: sciris/sciris