
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2020-03-27T19:45:10+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "8fcf54d2134f8ac942f7cdc5c1e55f02f8f7cdbc",
 "version": "0.9.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
