[tool.poetry]
name = "django-enhanced-settings"
version = "0.2.0"
description = "Allow for more complex and dynamic settings for Django"
authors = ["Nihaal Sangha <18350092+OrangutanGaming@users.noreply.github.com>"]
license = "MIT"
include = ["LICENSE"]
readme = "README.md"
repository = "https://github.com/OrangutanGaming/django-enhanced-settings"

[tool.poetry.dependencies]
python = "^3.8"
google-cloud-secret-manager = {version = "^0.2.0", optional = true}

[tool.poetry.dev-dependencies]
pytest = "^5.4.1"
pytest-cov = "^2.8.1"

[tool.poetry.extras]
cloud-secret-manager = ["google-cloud-secret-manager"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
