language: python
python:
- 3.6
- 2.7

install:
 - sudo apt-get install python-biopython pymol
 - pip install -r docs/requirements.txt

script:
 - bash test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
   email:
     - magnus@genesilico.pl
