# coding: utf-8

"""
    Edge Impulse API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.user_api import UserApi  # noqa: E501
from openapi_client.rest import ApiException


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.user_api.UserApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_activate_current_user(self):
        """Test case for activate_current_user

        Activate current user  # noqa: E501
        """
        pass

    def test_activate_user(self):
        """Test case for activate_user

        Activate user  # noqa: E501
        """
        pass

    def test_create_user(self):
        """Test case for create_user

        Create user  # noqa: E501
        """
        pass

    def test_delete_current_user(self):
        """Test case for delete_current_user

        Delete current user  # noqa: E501
        """
        pass

    def test_delete_user(self):
        """Test case for delete_user

        Delete user  # noqa: E501
        """
        pass

    def test_get_current_user(self):
        """Test case for get_current_user

        Get current user  # noqa: E501
        """
        pass

    def test_get_user(self):
        """Test case for get_user

        Get user  # noqa: E501
        """
        pass

    def test_list_emails_current_user(self):
        """Test case for list_emails_current_user

        List emails  # noqa: E501
        """
        pass

    def test_list_emails_user(self):
        """Test case for list_emails_user

        List emails  # noqa: E501
        """
        pass

    def test_request_activation_code_current_user(self):
        """Test case for request_activation_code_current_user

        Request activation code  # noqa: E501
        """
        pass

    def test_request_activation_code_user(self):
        """Test case for request_activation_code_user

        Request activation code  # noqa: E501
        """
        pass

    def test_request_reset_password(self):
        """Test case for request_reset_password

        Request reset password  # noqa: E501
        """
        pass

    def test_reset_password(self):
        """Test case for reset_password

        Reset password  # noqa: E501
        """
        pass

    def test_update_current_user(self):
        """Test case for update_current_user

        Update current user  # noqa: E501
        """
        pass

    def test_update_user(self):
        """Test case for update_user

        Update user  # noqa: E501
        """
        pass

    def test_verify_reset_password(self):
        """Test case for verify_reset_password

        Verify reset password code  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
