# coding: utf-8

"""
    Edge Impulse API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import edge_impulse_sdk
from edge_impulse_sdk.models.get_organization_data_item_response_all_of_data import GetOrganizationDataItemResponseAllOfData  # noqa: E501
from edge_impulse_sdk.rest import ApiException


class TestGetOrganizationDataItemResponseAllOfData(unittest.TestCase):
    """GetOrganizationDataItemResponseAllOfData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetOrganizationDataItemResponseAllOfData(self):
        """Test GetOrganizationDataItemResponseAllOfData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = edge_impulse_sdk.models.get_organization_data_item_response_all_of_data.GetOrganizationDataItemResponseAllOfData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
