# coding: utf-8

"""
    Edge Impulse API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.dsp_group_item_select_options import DSPGroupItemSelectOptions  # noqa: E501
from openapi_client.rest import ApiException


class TestDSPGroupItemSelectOptions(unittest.TestCase):
    """DSPGroupItemSelectOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDSPGroupItemSelectOptions(self):
        """Test DSPGroupItemSelectOptions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.dsp_group_item_select_options.DSPGroupItemSelectOptions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
