# coding: utf-8

"""
    Edge Impulse API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import edge_impulse_sdk
from edge_impulse_sdk.models.verify_dsp_block_url_response_all_of_block import VerifyDspBlockUrlResponseAllOfBlock  # noqa: E501
from edge_impulse_sdk.rest import ApiException


class TestVerifyDspBlockUrlResponseAllOfBlock(unittest.TestCase):
    """VerifyDspBlockUrlResponseAllOfBlock unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVerifyDspBlockUrlResponseAllOfBlock(self):
        """Test VerifyDspBlockUrlResponseAllOfBlock"""
        # FIXME: construct object with mandatory attributes with example values
        # model = edge_impulse_sdk.models.verify_dsp_block_url_response_all_of_block.VerifyDspBlockUrlResponseAllOfBlock()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
