[tool.poetry]
name = "udpy"
version = "1.0.0"
description = "Urban dictionary API wrapper for Python"
authors = ["prostomarkeloff"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.6"
requests = "^2.23.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
