# coding: utf-8

"""
    Edge Impulse API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from edge_impulse_sdk.configuration import Configuration


class KerasResponseAllOf(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'dependencies': 'DependencyData',
        'trained': 'bool',
        'name': 'str',
        'script': 'str',
        'minimum_confidence_rating': 'float',
        'mode': 'str',
        'visual_layers': 'list[KerasVisualLayer]',
        'training_cycles': 'int',
        'learning_rate': 'float'
    }

    attribute_map = {
        'dependencies': 'dependencies',
        'trained': 'trained',
        'name': 'name',
        'script': 'script',
        'minimum_confidence_rating': 'minimumConfidenceRating',
        'mode': 'mode',
        'visual_layers': 'visualLayers',
        'training_cycles': 'trainingCycles',
        'learning_rate': 'learningRate'
    }

    def __init__(self, dependencies=None, trained=None, name=None, script=None, minimum_confidence_rating=None, mode=None, visual_layers=None, training_cycles=None, learning_rate=None, local_vars_configuration=None):  # noqa: E501
        """KerasResponseAllOf - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._dependencies = None
        self._trained = None
        self._name = None
        self._script = None
        self._minimum_confidence_rating = None
        self._mode = None
        self._visual_layers = None
        self._training_cycles = None
        self._learning_rate = None
        self.discriminator = None

        self.dependencies = dependencies
        self.trained = trained
        self.name = name
        self.script = script
        self.minimum_confidence_rating = minimum_confidence_rating
        self.mode = mode
        self.visual_layers = visual_layers
        self.training_cycles = training_cycles
        self.learning_rate = learning_rate

    @property
    def dependencies(self):
        """Gets the dependencies of this KerasResponseAllOf.  # noqa: E501


        :return: The dependencies of this KerasResponseAllOf.  # noqa: E501
        :rtype: DependencyData
        """
        return self._dependencies

    @dependencies.setter
    def dependencies(self, dependencies):
        """Sets the dependencies of this KerasResponseAllOf.


        :param dependencies: The dependencies of this KerasResponseAllOf.  # noqa: E501
        :type: DependencyData
        """
        if self.local_vars_configuration.client_side_validation and dependencies is None:  # noqa: E501
            raise ValueError("Invalid value for `dependencies`, must not be `None`")  # noqa: E501

        self._dependencies = dependencies

    @property
    def trained(self):
        """Gets the trained of this KerasResponseAllOf.  # noqa: E501

        Whether the block is trained  # noqa: E501

        :return: The trained of this KerasResponseAllOf.  # noqa: E501
        :rtype: bool
        """
        return self._trained

    @trained.setter
    def trained(self, trained):
        """Sets the trained of this KerasResponseAllOf.

        Whether the block is trained  # noqa: E501

        :param trained: The trained of this KerasResponseAllOf.  # noqa: E501
        :type: bool
        """
        if self.local_vars_configuration.client_side_validation and trained is None:  # noqa: E501
            raise ValueError("Invalid value for `trained`, must not be `None`")  # noqa: E501

        self._trained = trained

    @property
    def name(self):
        """Gets the name of this KerasResponseAllOf.  # noqa: E501


        :return: The name of this KerasResponseAllOf.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this KerasResponseAllOf.


        :param name: The name of this KerasResponseAllOf.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and name is None:  # noqa: E501
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def script(self):
        """Gets the script of this KerasResponseAllOf.  # noqa: E501

        The Keras script. This script might be empty if the mode is visual.  # noqa: E501

        :return: The script of this KerasResponseAllOf.  # noqa: E501
        :rtype: str
        """
        return self._script

    @script.setter
    def script(self, script):
        """Sets the script of this KerasResponseAllOf.

        The Keras script. This script might be empty if the mode is visual.  # noqa: E501

        :param script: The script of this KerasResponseAllOf.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and script is None:  # noqa: E501
            raise ValueError("Invalid value for `script`, must not be `None`")  # noqa: E501

        self._script = script

    @property
    def minimum_confidence_rating(self):
        """Gets the minimum_confidence_rating of this KerasResponseAllOf.  # noqa: E501

        Minimum confidence rating required for the neural network. Scores below this confidence are tagged as uncertain.  # noqa: E501

        :return: The minimum_confidence_rating of this KerasResponseAllOf.  # noqa: E501
        :rtype: float
        """
        return self._minimum_confidence_rating

    @minimum_confidence_rating.setter
    def minimum_confidence_rating(self, minimum_confidence_rating):
        """Sets the minimum_confidence_rating of this KerasResponseAllOf.

        Minimum confidence rating required for the neural network. Scores below this confidence are tagged as uncertain.  # noqa: E501

        :param minimum_confidence_rating: The minimum_confidence_rating of this KerasResponseAllOf.  # noqa: E501
        :type: float
        """
        if self.local_vars_configuration.client_side_validation and minimum_confidence_rating is None:  # noqa: E501
            raise ValueError("Invalid value for `minimum_confidence_rating`, must not be `None`")  # noqa: E501

        self._minimum_confidence_rating = minimum_confidence_rating

    @property
    def mode(self):
        """Gets the mode of this KerasResponseAllOf.  # noqa: E501

        The mode (visual or expert) to use for editing this network.  # noqa: E501

        :return: The mode of this KerasResponseAllOf.  # noqa: E501
        :rtype: str
        """
        return self._mode

    @mode.setter
    def mode(self, mode):
        """Sets the mode of this KerasResponseAllOf.

        The mode (visual or expert) to use for editing this network.  # noqa: E501

        :param mode: The mode of this KerasResponseAllOf.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and mode is None:  # noqa: E501
            raise ValueError("Invalid value for `mode`, must not be `None`")  # noqa: E501
        allowed_values = ["visual", "expert"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and mode not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `mode` ({0}), must be one of {1}"  # noqa: E501
                .format(mode, allowed_values)
            )

        self._mode = mode

    @property
    def visual_layers(self):
        """Gets the visual_layers of this KerasResponseAllOf.  # noqa: E501

        The visual layers (if in visual mode) for the neural network. This will be an empty array when in expert mode.  # noqa: E501

        :return: The visual_layers of this KerasResponseAllOf.  # noqa: E501
        :rtype: list[KerasVisualLayer]
        """
        return self._visual_layers

    @visual_layers.setter
    def visual_layers(self, visual_layers):
        """Sets the visual_layers of this KerasResponseAllOf.

        The visual layers (if in visual mode) for the neural network. This will be an empty array when in expert mode.  # noqa: E501

        :param visual_layers: The visual_layers of this KerasResponseAllOf.  # noqa: E501
        :type: list[KerasVisualLayer]
        """
        if self.local_vars_configuration.client_side_validation and visual_layers is None:  # noqa: E501
            raise ValueError("Invalid value for `visual_layers`, must not be `None`")  # noqa: E501

        self._visual_layers = visual_layers

    @property
    def training_cycles(self):
        """Gets the training_cycles of this KerasResponseAllOf.  # noqa: E501

        Number of training cycles. If in expert mode this will be 0.  # noqa: E501

        :return: The training_cycles of this KerasResponseAllOf.  # noqa: E501
        :rtype: int
        """
        return self._training_cycles

    @training_cycles.setter
    def training_cycles(self, training_cycles):
        """Sets the training_cycles of this KerasResponseAllOf.

        Number of training cycles. If in expert mode this will be 0.  # noqa: E501

        :param training_cycles: The training_cycles of this KerasResponseAllOf.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and training_cycles is None:  # noqa: E501
            raise ValueError("Invalid value for `training_cycles`, must not be `None`")  # noqa: E501

        self._training_cycles = training_cycles

    @property
    def learning_rate(self):
        """Gets the learning_rate of this KerasResponseAllOf.  # noqa: E501

        Learning rate (between 0 and 1). If in expert mode this will be 0.  # noqa: E501

        :return: The learning_rate of this KerasResponseAllOf.  # noqa: E501
        :rtype: float
        """
        return self._learning_rate

    @learning_rate.setter
    def learning_rate(self, learning_rate):
        """Sets the learning_rate of this KerasResponseAllOf.

        Learning rate (between 0 and 1). If in expert mode this will be 0.  # noqa: E501

        :param learning_rate: The learning_rate of this KerasResponseAllOf.  # noqa: E501
        :type: float
        """
        if self.local_vars_configuration.client_side_validation and learning_rate is None:  # noqa: E501
            raise ValueError("Invalid value for `learning_rate`, must not be `None`")  # noqa: E501

        self._learning_rate = learning_rate

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, KerasResponseAllOf):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, KerasResponseAllOf):
            return True

        return self.to_dict() != other.to_dict()
