# coding: utf-8

"""
    Edge Impulse API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from edge_impulse_sdk.configuration import Configuration


class StartTrainingRequestAnomaly(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'axes': 'list[int]',
        'cluster_count': 'int',
        'minimum_confidence_rating': 'float'
    }

    attribute_map = {
        'axes': 'axes',
        'cluster_count': 'clusterCount',
        'minimum_confidence_rating': 'minimumConfidenceRating'
    }

    def __init__(self, axes=None, cluster_count=None, minimum_confidence_rating=None, local_vars_configuration=None):  # noqa: E501
        """StartTrainingRequestAnomaly - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._axes = None
        self._cluster_count = None
        self._minimum_confidence_rating = None
        self.discriminator = None

        self.axes = axes
        self.cluster_count = cluster_count
        self.minimum_confidence_rating = minimum_confidence_rating

    @property
    def axes(self):
        """Gets the axes of this StartTrainingRequestAnomaly.  # noqa: E501

        Which axes (indexes from DSP script) to include in the training set  # noqa: E501

        :return: The axes of this StartTrainingRequestAnomaly.  # noqa: E501
        :rtype: list[int]
        """
        return self._axes

    @axes.setter
    def axes(self, axes):
        """Sets the axes of this StartTrainingRequestAnomaly.

        Which axes (indexes from DSP script) to include in the training set  # noqa: E501

        :param axes: The axes of this StartTrainingRequestAnomaly.  # noqa: E501
        :type: list[int]
        """
        if self.local_vars_configuration.client_side_validation and axes is None:  # noqa: E501
            raise ValueError("Invalid value for `axes`, must not be `None`")  # noqa: E501

        self._axes = axes

    @property
    def cluster_count(self):
        """Gets the cluster_count of this StartTrainingRequestAnomaly.  # noqa: E501

        Number of clusters  # noqa: E501

        :return: The cluster_count of this StartTrainingRequestAnomaly.  # noqa: E501
        :rtype: int
        """
        return self._cluster_count

    @cluster_count.setter
    def cluster_count(self, cluster_count):
        """Sets the cluster_count of this StartTrainingRequestAnomaly.

        Number of clusters  # noqa: E501

        :param cluster_count: The cluster_count of this StartTrainingRequestAnomaly.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and cluster_count is None:  # noqa: E501
            raise ValueError("Invalid value for `cluster_count`, must not be `None`")  # noqa: E501

        self._cluster_count = cluster_count

    @property
    def minimum_confidence_rating(self):
        """Gets the minimum_confidence_rating of this StartTrainingRequestAnomaly.  # noqa: E501

        Minimum confidence rating required before tagging as anomaly  # noqa: E501

        :return: The minimum_confidence_rating of this StartTrainingRequestAnomaly.  # noqa: E501
        :rtype: float
        """
        return self._minimum_confidence_rating

    @minimum_confidence_rating.setter
    def minimum_confidence_rating(self, minimum_confidence_rating):
        """Sets the minimum_confidence_rating of this StartTrainingRequestAnomaly.

        Minimum confidence rating required before tagging as anomaly  # noqa: E501

        :param minimum_confidence_rating: The minimum_confidence_rating of this StartTrainingRequestAnomaly.  # noqa: E501
        :type: float
        """
        if self.local_vars_configuration.client_side_validation and minimum_confidence_rating is None:  # noqa: E501
            raise ValueError("Invalid value for `minimum_confidence_rating`, must not be `None`")  # noqa: E501

        self._minimum_confidence_rating = minimum_confidence_rating

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StartTrainingRequestAnomaly):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, StartTrainingRequestAnomaly):
            return True

        return self.to_dict() != other.to_dict()
