[tool.poetry]
name = "basicsql"
version = "0.1.1"
description = ""
authors = ["Ramon Brandt <devramon22@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.6.1"
sqlalchemy = "^1.3.13"
pandas = "^1.0.1"
numpy = "^1.18.1"
jinjasql = "^0.1.7"
cx_Oracle = {version = "^7.3.0", optional = true}
psycopg2 = {version = "^2.8.4", optional = true}
pyodbc = {version = "^4.0.30", optional = true}
pymysql = {version = "^0.9.3", optional = true}

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pylint = "^2.4.4"
mypy = "^0.761"
black = "^19.10b0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
