# vim ft=yaml
language: python
python:
  - 3.6
  - 3.7
  - 3.8

services:
  - docker

env:
  global:
    - BUILD_TYPE="src"
    - DOCKER_IMAGE="poldracklab/fmriprep:latest"
    - TEST_DATA_HOME="$HOME/.nitransforms/testdata"

matrix:
  include:
  - python: 3.7
    env: BUILD_TYPE="docker"

cache:
  directories:
    - $HOME/.nitransforms/testdata

before_install:
  - |
    if [[ "$( ls -A $TEST_DATA_HOME )" == "" ]]; then
      mkdir -p $HOME/.nitransforms
      wget --retry-connrefused --waitretry=5 --read-timeout=20 --timeout=15 -t 0 -q \
        -O data.zip "https://files.osf.io/v1/resources/fvuh8/providers/osfstorage/5e7d5b65c3f8d300bafa05e0/?zip="
      unzip -d $TEST_DATA_HOME data.zip
    else
      echo "Dataset was cached"
    fi
    if [ ${BUILD_TYPE} == "docker" ]; then
      CI_ENV=`bash <(curl -s https://codecov.io/env)`
      docker pull ${DOCKER_IMAGE}  # pull latest release
      docker run $CI_ENV -v $TEST_DATA_HOME:/data -e TEST_DATA_HOME=/data -itd --name fmriprep --entrypoint=/bin/bash -v `pwd`:/opt/nt -w /opt/nt ${DOCKER_IMAGE}
      docker exec fmriprep sh -c 'echo "cHJpbnRmICJrcnp5c3p0b2YuZ29yZ29sZXdza2lAZ21haWwuY29tXG41MTcyXG4gKkN2dW12RVYzelRmZ1xuRlM1Si8yYzFhZ2c0RVxuIiA+IC9vcHQvZnJlZXN1cmZlci9saWNlbnNlLnR4dAo=" | base64 -d | sh'
    fi

install:
  # pull the latest release
  - |
    if [ ${BUILD_TYPE} == "docker" ]; then
      # update nibabel pin
      docker exec fmriprep pip install --upgrade git+https://github.com/nipy/nibabel@cd48bf05bc567387afe4504eda1da15324bb616f
      docker exec fmriprep pip install -e /opt/nt[test]
    elif [ ${BUILD_TYPE} == "src" ]; then
      pip install -U -e .[test]
    fi

script:
  - |
    if [ ${BUILD_TYPE} == "docker" ]; then
      docker exec fmriprep pytest -v --cov nitransforms --cov-config /opt/nt/.coveragerc --cov-report xml:/opt/nt/cov.xml --doctest-modules /opt/nt/nitransforms
    elif [ ${BUILD_TYPE} == "src" ]; then
      pytest -v --cov nitransforms --cov-config `pwd`/.coveragerc --cov-report xml:`pwd`/cov.xml --doctest-modules nitransforms
    fi

after_success:
  - |
    if [ ${BUILD_TYPE} == "docker" ]; then
      docker exec fmriprep codecov --root /opt/nt -f /opt/nt/cov.xml -F unittests
      docker rm -f fmriprep
    elif [ ${BUILD_TYPE} == "src" ]; then
      codecov --file `pwd`/cov.xml --flags unittests -e TRAVIS_JOB_NUMBER
    fi
