language: c

os: linux

addons:
    apt:
        packages:
            - texlive-latex-extra
            - dvipng
            - texlive-fonts-recommended

env:
    global:
        - PYTHON_VERSION=3.7
        - ASTROPY_VERSION=stable
        - NUMPY_VERSION=1.18
        - CONDA_DEPENDENCIES='scipy scikit-learn matplotlib'
        - PIP_DEPENDENCIES='pytest-doctestplus>=0.3 pytest-remotedata pytest-astropy-header pymc3'
        - PIP_ALL_DEPENDENCIES='scipy scikit-learn matplotlib pytest-astropy pymc3'
        - DEBUG=True
        - SCRIPT_CMD='pytest astroML'

jobs:
    fast_finish: true

    include:
        - env: NUMPY_VERSION=1.17 SCRIPT_CMD='pytest astroML --remote-data'

        - env: NUMPY_VERSION=1.16

        # Use minimum version for everything
        - env: PYTHON_VERSION=3.5 NUMPY_VERSION=1.13 ASTROPY_VERSION=''
               PIP_DEPENDENCIES='scipy==0.18 scikit-learn==0.18 matplotlib==3.0 pytest-astropy astropy==3.0 pymc3 cftime<1.1.1.1'
               CONDA_DEPENDENCIES=''

        - env: PYTHON_VERSION=3.6 SCRIPT_CMD='make -C doc html' PIP_DEPENDENCIES='sphinx'

        - env: PYTHON_VERSION=3.8 PIP_DEPENDENCIES=$PIP_ALL_DEPENDENCIES
               CONDA_DEPENDENCIES=""

#    allow_failures:


install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh
    - python setup.py install

script:
    - $SCRIPT_CMD
