---
- include_tasks: register.yml
  when: enable_keystone | bool and
        (inventory_hostname in groups['ironic-api'] or
        inventory_hostname in groups['ironic-inspector'])

- include_tasks: config.yml
  when: inventory_hostname in groups['ironic-api'] or
        inventory_hostname in groups['ironic-conductor'] or
        inventory_hostname in groups['ironic-inspector'] or
        inventory_hostname in groups['ironic-pxe'] or
        inventory_hostname in groups['ironic-ipxe']

- include_tasks: clone.yml
  when: ironic_dev_mode | bool

- include_tasks: bootstrap.yml
  when: inventory_hostname in groups['ironic-api'] or
        inventory_hostname in groups['ironic-inspector'] or
        inventory_hostname in groups['ironic-pxe']

- name: Flush handlers
  meta: flush_handlers
