# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(748, 463)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.searchEdit = QtWidgets.QLineEdit(self.frame_2)
        self.searchEdit.setObjectName("searchEdit")
        self.horizontalLayout_2.addWidget(self.searchEdit)
        self.stopButton = QtWidgets.QPushButton(self.frame_2)
        self.stopButton.setMaximumSize(QtCore.QSize(35, 16777215))
        self.stopButton.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:1, stop:0 rgba(255, 0, 0, 255), stop:0.479904 rgba(255, 0, 0, 255), stop:0.522685 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));")
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout_2.addWidget(self.stopButton)
        self.backendEdit = QtWidgets.QComboBox(self.frame_2)
        self.backendEdit.setObjectName("backendEdit")
        self.horizontalLayout_2.addWidget(self.backendEdit)
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.countSpin = QtWidgets.QSpinBox(self.frame_2)
        self.countSpin.setObjectName("countSpin")
        self.horizontalLayout_2.addWidget(self.countSpin)
        self.verticalLayout.addWidget(self.frame_2)
        self.resultsTab = QtWidgets.QTabWidget(self.centralwidget)
        self.resultsTab.setTabsClosable(True)
        self.resultsTab.setMovable(True)
        self.resultsTab.setObjectName("resultsTab")
        self.verticalLayout.addWidget(self.resultsTab)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.showTCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.showTCheck.setObjectName("showTCheck")
        self.horizontalLayout_3.addWidget(self.showTCheck)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.idEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.idEdit.setObjectName("idEdit")
        self.horizontalLayout_3.addWidget(self.idEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 748, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionBackends = QtWidgets.QAction(MainWindow)
        self.actionBackends.setObjectName("actionBackends")
        self.toolBar.addAction(self.actionBackends)

        self.retranslateUi(MainWindow)
        self.resultsTab.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "QCookboob"))
        self.label.setText(_translate("MainWindow", "Search: "))
        self.stopButton.setText(_translate("MainWindow", "stop"))
        self.label_3.setToolTip(_translate("MainWindow", "<html><head/><body><p>Maximum results by backend</p><p>0 = no limit</p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "max results"))
        self.countSpin.setToolTip(_translate("MainWindow", "<html><head/><body><p>Maximum results by backend</p><p>0 = no limit</p></body></html>"))
        self.showTCheck.setText(_translate("MainWindow", "Show thumbnails"))
        self.label_2.setText(_translate("MainWindow", "search by ID:"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionBackends.setText(_translate("MainWindow", "Backends"))
