[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "NuRadioReco"
author = "Christian Glaser"
author-email = "work@c-glaser.de"
home-page = "https://github.com/nu-radio/NuRadioReco"
classifiers = ["License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)"]
requires = [
    "tinydb",
    "tinydb-serialization",
    "aenum",
    "astropy<=2.0.14",
    "radiotools >=0.2.0",
    "h5py",
    "peakutils",
    "requests"
]
requires-python=">3.4"

[tool.flit.metadata.requires-extra]
doc = ["sphinx"]

