repos:
- repo: https://github.com/psf/black
  rev: 19.10b0
  hooks:
  - id: black
    args:
    - --line-length=79
    - --quiet
    - --safe
    - --skip-string-normalization
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.5.0
  hooks:
  - id: double-quote-string-fixer
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: debug-statements
    language_version: python3
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.7.9
  hooks:
  - id: flake8
    language_version: python3
    additional_dependencies:
    - flake8-bugbear
