[tool.poetry]
name = "ask_schools"
version = "0.3.4"
description = "Ask Scholars Portal School Name Conversion"
authors = ["Guinsly Mondesir <guinslym@gmail.com>"]
keywords = ["Ask", "Scholars Portal", "Ontario"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/guinslym/ask_schools"
repository = "https://github.com/guinslym/ask_schools"
classifiers = [
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Documentation",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Software Development :: Quality Assurance",
]
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = "^3.4"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
