name: Publish Docker arm64
on:
  push:
    branches:
      - master
    paths:
      - 'Dockerfile.arm64'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: pandaofficial/timeswipe_py_arm64
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: Dockerfile.arm64
