version: "2.2"
services:
  ursim:
    image: arranhs/dockursim:latest
    environment:
      - ROBOT_MODEL=UR5
    ports:
      - 8080:8080
      - 29999:29999
      - 30001-30004:30001-30004
    volumes:
      - dockursim:/ursim
      - ./programs:/ursim/programs

    privileged: true
    cpus: 1

volumes:
  dockursim:
    driver: local

# Open localhost:8080 to run simulator
