# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(582, 463)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.searchEdit = QtWidgets.QLineEdit(self.frame_2)
        self.searchEdit.setObjectName("searchEdit")
        self.horizontalLayout_2.addWidget(self.searchEdit)
        self.sortbyEdit = QtWidgets.QComboBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sortbyEdit.sizePolicy().hasHeightForWidth())
        self.sortbyEdit.setSizePolicy(sizePolicy)
        self.sortbyEdit.setObjectName("sortbyEdit")
        self.sortbyEdit.addItem("")
        self.sortbyEdit.addItem("")
        self.sortbyEdit.addItem("")
        self.sortbyEdit.addItem("")
        self.horizontalLayout_2.addWidget(self.sortbyEdit)
        self.backendEdit = QtWidgets.QComboBox(self.frame_2)
        self.backendEdit.setObjectName("backendEdit")
        self.horizontalLayout_2.addWidget(self.backendEdit)
        self.verticalLayout.addWidget(self.frame_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.sfwCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.sfwCheckBox.setChecked(True)
        self.sfwCheckBox.setObjectName("sfwCheckBox")
        self.horizontalLayout_3.addWidget(self.sfwCheckBox)
        self.nsfwCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.nsfwCheckBox.setChecked(True)
        self.nsfwCheckBox.setObjectName("nsfwCheckBox")
        self.horizontalLayout_3.addWidget(self.nsfwCheckBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaContent = QtWidgets.QWidget()
        self.scrollAreaContent.setGeometry(QtCore.QRect(0, 0, 560, 230))
        self.scrollAreaContent.setObjectName("scrollAreaContent")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaContent)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea.setWidget(self.scrollAreaContent)
        self.verticalLayout.addWidget(self.scrollArea)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.urlEdit = QtWidgets.QLineEdit(self.frame_3)
        self.urlEdit.setObjectName("urlEdit")
        self.horizontalLayout.addWidget(self.urlEdit)
        self.verticalLayout.addWidget(self.frame_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 582, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionBackends = QtWidgets.QAction(MainWindow)
        self.actionBackends.setObjectName("actionBackends")
        self.toolBar.addAction(self.actionBackends)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "QVideoob"))
        self.label.setText(_translate("MainWindow", "Search: "))
        self.sortbyEdit.setItemText(0, _translate("MainWindow", "Relevance"))
        self.sortbyEdit.setItemText(1, _translate("MainWindow", "Rating"))
        self.sortbyEdit.setItemText(2, _translate("MainWindow", "Duration"))
        self.sortbyEdit.setItemText(3, _translate("MainWindow", "Date"))
        self.label_3.setText(_translate("MainWindow", "Display:"))
        self.sfwCheckBox.setText(_translate("MainWindow", "SFW"))
        self.nsfwCheckBox.setText(_translate("MainWindow", "NSFW"))
        self.label_2.setText(_translate("MainWindow", "URL: "))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionBackends.setText(_translate("MainWindow", "Backends"))
