# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'minivideo.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MiniVideo(object):
    def setupUi(self, MiniVideo):
        MiniVideo.setObjectName("MiniVideo")
        MiniVideo.resize(464, 132)
        MiniVideo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        MiniVideo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.horizontalLayout = QtWidgets.QHBoxLayout(MiniVideo)
        self.horizontalLayout.setContentsMargins(9, 5, -1, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.imageLabel = QtWidgets.QLabel(MiniVideo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageLabel.sizePolicy().hasHeightForWidth())
        self.imageLabel.setSizePolicy(sizePolicy)
        self.imageLabel.setText("")
        self.imageLabel.setObjectName("imageLabel")
        self.horizontalLayout.addWidget(self.imageLabel)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label_5 = QtWidgets.QLabel(MiniVideo)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.titleLabel = QtWidgets.QLabel(MiniVideo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleLabel.sizePolicy().hasHeightForWidth())
        self.titleLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.titleLabel.setFont(font)
        self.titleLabel.setObjectName("titleLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.titleLabel)
        self.label_8 = QtWidgets.QLabel(MiniVideo)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.durationLabel = QtWidgets.QLabel(MiniVideo)
        self.durationLabel.setObjectName("durationLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.durationLabel)
        self.label_4 = QtWidgets.QLabel(MiniVideo)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.authorLabel = QtWidgets.QLabel(MiniVideo)
        self.authorLabel.setObjectName("authorLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.authorLabel)
        self.label_2 = QtWidgets.QLabel(MiniVideo)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.dateLabel = QtWidgets.QLabel(MiniVideo)
        self.dateLabel.setObjectName("dateLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.dateLabel)
        self.label_3 = QtWidgets.QLabel(MiniVideo)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.ratingLabel = QtWidgets.QLabel(MiniVideo)
        self.ratingLabel.setObjectName("ratingLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.ratingLabel)
        self.label = QtWidgets.QLabel(MiniVideo)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label)
        self.backendLabel = QtWidgets.QLabel(MiniVideo)
        self.backendLabel.setObjectName("backendLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.backendLabel)
        self.horizontalLayout.addLayout(self.formLayout)

        self.retranslateUi(MiniVideo)
        QtCore.QMetaObject.connectSlotsByName(MiniVideo)

    def retranslateUi(self, MiniVideo):
        _translate = QtCore.QCoreApplication.translate
        MiniVideo.setWindowTitle(_translate("MiniVideo", "Form"))
        self.label_5.setText(_translate("MiniVideo", "Title"))
        self.titleLabel.setText(_translate("MiniVideo", "TextLabel"))
        self.label_8.setText(_translate("MiniVideo", "Duration"))
        self.durationLabel.setText(_translate("MiniVideo", "TextLabel"))
        self.label_4.setText(_translate("MiniVideo", "Author"))
        self.authorLabel.setText(_translate("MiniVideo", "TextLabel"))
        self.label_2.setText(_translate("MiniVideo", "Date"))
        self.dateLabel.setText(_translate("MiniVideo", "TextLabel"))
        self.label_3.setText(_translate("MiniVideo", "Rating"))
        self.ratingLabel.setText(_translate("MiniVideo", "TextLabel"))
        self.label.setText(_translate("MiniVideo", "Where"))
        self.backendLabel.setText(_translate("MiniVideo", "TextLabel"))
