
# ####################################
# List of RAPyDo supported services
#
# NOTE: order matters
# ####################################

  # sqlalchemy relational databases
- name: sqlalchemy
  load_models: 1
  prefix: alchemy
  extension: flask_alchemy
  class: SqlAlchemy

  # neo4j graphdb ORM
- name: neo4j
  load_models: 1
  prefix: neo4j
  extension: flask_neo4j
  class: NeoModel

  # celery tasks
- name: celery
  load_models: 0
  prefix: celery
  extension: flask_celery
  class: CeleryExt

  # mongo database
- name: mongo
  load_models: 1
  prefix: mongo
  extension: flask_mongo
  class: MongoExt

  # rabbitmq message queue
- name: rabbit
  load_models: 0
  prefix: rabbitmq
  extension: flask_rabbit
  class: RabbitExt

  # irods file system commands
- name: irods
  load_models: 0
  prefix: irods
  extension: flask_irods
  class: IrodsPythonExt

  # pushpin websockets and HTTP stream
- name: pushpin
  load_models: 0
  prefix: pushpin
  extension: flask_pushpin
  class: PushpinExt

##############################
# # OTHERS?
# "elastic",
# "redis",

# ##############################
# NOTE: THIS HAS TO BE THE LAST ONE
# ##############################

  # authentication
- name: authentication
  load_models: 0
  prefix: auth
  extension: flask_auth
  class: Authenticator
