---
- include_tasks: register.yml
  when: inventory_hostname in groups['freezer-api']

- include_tasks: config.yml
  when: inventory_hostname in groups['freezer-api'] or
        inventory_hostname in groups['freezer-scheduler']

- include_tasks: bootstrap_service.yml
  when: inventory_hostname in groups['freezer-api']

- name: Flush handlers
  meta: flush_handlers
