[tool.poetry]
name = "coderadio"
version = "0.0.dev19"
description = "Terminal radio for geeks."
authors = ["André P. Santos <andreztz@gmail.com>"]
license = "MIT"
readme = "README.md"
keywords = ["player", "radio", "browser", "web", "terminal"]
classifiers = [
    "Development Status :: 1 - Planning",
    "Intended Audience :: End Users/Desktop",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Multimedia :: Sound/Audio :: Players",
    "Topic :: Utilities"
]

[tool.poetry.dependencies]
python = "^3.8"
prompt-toolkit = "3.0.4"
pyradios = "^0.0.21"
notify-send = "^0.0.13"
pygments = "^2.6.1"
streamscrobbler3 = "^0.0.4"
python-mpv = "^0.4.5"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
coderadio = "coderadio.__main__:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
