
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-03-25T16:20:55-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "4b9f83b58f34f2a457324a06fd29500ee7c81764",
 "version": "0.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
