---
- name: "declaring output vars for topology outputs of gce"
  set_fact:
    topology_outputs_gcloud_gce: []

- name: "Initiating  Provisioning of resources in gcloud resource group"
  include: provision_resource_group.yml res_grp={{ item }}
  with_items:
  - "{{ resources }}"
