[tool.poetry]
name = "poetry-project"
version = "0.3.0"
description = "Read poetry project information such as name, version and description."
authors = ["Julian Stier <mail@julian-stier.de>"]
include = [
    "pyproject.toml",
    "README.md"
]

[tool.poetry.dependencies]
python = "^3.5"
tomlkit = "^0.5.11"
importlib-resources = "^1.4.0"
importlib-metadata = "^1.5.0"

[tool.poetry.dev-dependencies]
pytest = "^5.4.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
