
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-01T14:38:52+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "3e6ec0e92be5a3bbc38ebd2bf6ed3f7aa0ceb5bd",
 "version": "0.4.108"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
