[tool.poetry]
name = "gcs-aio-mapper"
license = "MIT"
version = "0.1.0"
description = "An mutable mapping interface to GCS leveraging asyncio"
authors = ["Noah D. Brenowitz <nbren12@gmail.com>"]
repository = "https://github.com/nbren12/gcs_aio_mapper"
homepage = "https://github.com/nbren12/gcs_aio_mapper"
readme = "README.rst"

[tool.poetry.dependencies]
python = "^3.7"
pylint = "^2.4.4"
aiohttp = "^3.6.2"
gcloud-aio-storage = "^5.2.2"
google-cloud-storage = "^1.26.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pylint = "^2.4.4"
black = "^19.10b0"
zarr = "^2.4.0"
ipython = "^7.13.0"
pytest-cov = "^2.8.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
