[tool.poetry]
name = "poetry-project"
version = "0.2.0"
description = ""
authors = ["Julian Stier <mail@julian-stier.de>"]

[tool.poetry.dependencies]
python = "^3.5"
tomlkit = "^0.5.11"
importlib-resources = "^1.4.0"

[tool.poetry.dev-dependencies]
pytest = "^5.4.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
