[tool.poetry]
name = "flask-yoyo"
version = "0.1.0"
description = "Dead-simple database migration with Yoyo for your Flask app"
authors = ["Étienne BERSAC <bersace03@cae.li>"]
license = "BSD-3-Clause"

[tool.poetry.dependencies]
python = "^3.5"
yoyo-migrations = "^7.0.2"
flask = "^1.1.1"

[tool.poetry.dev-dependencies]
psycopg2-binary = "^2.8.4"

[tool.poetry.plugins."flask.commands"]
yoyo = "flask_yoyo:cli"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
