[tool.poetry]
name = "coronaviruspy"
version = "0.3.0"
description = "CLI command for showing coronavirus info"
authors = ["Daniel Kukucz <daniel@kukucz.com>"]

[tool.poetry.dependencies]
python = "^3.7"
click = "^7.1.1"
requests = "^2.23.0"
bs4 = "^0.0.1"
termgraph = "^0.2.1"

[tool.poetry.dev-dependencies]
pytest = "^4.6"


[tool.poetry.scripts]
cinfo = "coronaviruspy.cli:coronavirus"


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
