
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-03-27T17:06:35+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "964282ec995c9123ffcd1587f312b008e8dfa583",
 "version": "0.12.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
