[tool.poetry]
name = "probabilistic-timed-automata"
version = "0.1.0"
description = "Probabilistic Timed Automata library for Python"
authors = ["Anand Balakrishnan <anandbala1597@gmail.com>"]

license = "MIT"

readme = "README.rst"
repository = "https://github.com/anand-bala/probabilistic-timed-automata.git"

packages = [
  { include = "pta" },
]

[tool.poetry.dependencies]
python = "^3.6"
attrs = "^19.3.0"
portion = "^2.0.0"

[tool.poetry.dev-dependencies]
autoflake = "^1.3.1"
black = "^19.10b0"
codecov = "^2.0.22"
mypy = "^0.761"
pytest = ">=5.0 <5.4"
pytest-cov = "^2.8.1"
pytest-flake8 = "^1.0.4"
pytest-sugar = "^0.9.2"
sphinx = {version = "^2.4.4", allow-prereleases = true}
sphinx-better-theme = "^0.1.5"
pytest-xdist = "^1.31.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
