# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'viewer.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Viewer(object):
    def setupUi(self, Viewer):
        Viewer.setObjectName("Viewer")
        Viewer.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Viewer)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 780, 503))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.view = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.view.setAlignment(QtCore.Qt.AlignCenter)
        self.view.setObjectName("view")
        self.horizontalLayout_2.addWidget(self.view)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.firstButton = QtWidgets.QToolButton(self.centralwidget)
        icon = QtGui.QIcon.fromTheme("go-first")
        self.firstButton.setIcon(icon)
        self.firstButton.setObjectName("firstButton")
        self.horizontalLayout.addWidget(self.firstButton)
        self.prevButton = QtWidgets.QToolButton(self.centralwidget)
        icon = QtGui.QIcon.fromTheme("go-previous")
        self.prevButton.setIcon(icon)
        self.prevButton.setObjectName("prevButton")
        self.horizontalLayout.addWidget(self.prevButton)
        self.posLabel = QtWidgets.QLabel(self.centralwidget)
        self.posLabel.setObjectName("posLabel")
        self.horizontalLayout.addWidget(self.posLabel)
        self.nextButton = QtWidgets.QToolButton(self.centralwidget)
        icon = QtGui.QIcon.fromTheme("go-next")
        self.nextButton.setIcon(icon)
        self.nextButton.setObjectName("nextButton")
        self.horizontalLayout.addWidget(self.nextButton)
        self.lastButton = QtWidgets.QToolButton(self.centralwidget)
        icon = QtGui.QIcon.fromTheme("go-last")
        self.lastButton.setIcon(icon)
        self.lastButton.setObjectName("lastButton")
        self.horizontalLayout.addWidget(self.lastButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        Viewer.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(Viewer)
        self.toolBar.setObjectName("toolBar")
        Viewer.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.menubar = QtWidgets.QMenuBar(Viewer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 19))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        Viewer.setMenuBar(self.menubar)
        self.actionClose = QtWidgets.QAction(Viewer)
        self.actionClose.setObjectName("actionClose")
        self.actionSaveImage = QtWidgets.QAction(Viewer)
        icon = QtGui.QIcon.fromTheme("document-save")
        self.actionSaveImage.setIcon(icon)
        self.actionSaveImage.setObjectName("actionSaveImage")
        self.actionFullSize = QtWidgets.QAction(Viewer)
        icon = QtGui.QIcon.fromTheme("zoom-original")
        self.actionFullSize.setIcon(icon)
        self.actionFullSize.setObjectName("actionFullSize")
        self.actionFitWindow = QtWidgets.QAction(Viewer)
        icon = QtGui.QIcon.fromTheme("zoom-fit-best")
        self.actionFitWindow.setIcon(icon)
        self.actionFitWindow.setObjectName("actionFitWindow")
        self.actionZoomOut = QtWidgets.QAction(Viewer)
        icon = QtGui.QIcon.fromTheme("zoom-out")
        self.actionZoomOut.setIcon(icon)
        self.actionZoomOut.setObjectName("actionZoomOut")
        self.actionZoomIn = QtWidgets.QAction(Viewer)
        icon = QtGui.QIcon.fromTheme("zoom-in")
        self.actionZoomIn.setIcon(icon)
        self.actionZoomIn.setObjectName("actionZoomIn")
        self.toolBar.addAction(self.actionZoomIn)
        self.toolBar.addAction(self.actionZoomOut)
        self.toolBar.addAction(self.actionFullSize)
        self.toolBar.addAction(self.actionFitWindow)
        self.menuFile.addAction(self.actionSaveImage)
        self.menuFile.addAction(self.actionClose)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(Viewer)
        QtCore.QMetaObject.connectSlotsByName(Viewer)

    def retranslateUi(self, Viewer):
        _translate = QtCore.QCoreApplication.translate
        Viewer.setWindowTitle(_translate("Viewer", "QGalleroob viewer"))
        self.firstButton.setText(_translate("Viewer", "|<"))
        self.prevButton.setText(_translate("Viewer", "<"))
        self.posLabel.setText(_translate("Viewer", "1/N"))
        self.nextButton.setText(_translate("Viewer", ">"))
        self.lastButton.setText(_translate("Viewer", ">|"))
        self.toolBar.setWindowTitle(_translate("Viewer", "toolBar"))
        self.menuFile.setTitle(_translate("Viewer", "File"))
        self.actionClose.setText(_translate("Viewer", "Close"))
        self.actionSaveImage.setText(_translate("Viewer", "Save image..."))
        self.actionFullSize.setText(_translate("Viewer", "Original size"))
        self.actionFullSize.setShortcut(_translate("Viewer", "G"))
        self.actionFitWindow.setText(_translate("Viewer", "Fit to window"))
        self.actionFitWindow.setShortcut(_translate("Viewer", "F"))
        self.actionZoomOut.setText(_translate("Viewer", "Zoom out"))
        self.actionZoomOut.setShortcut(_translate("Viewer", "-"))
        self.actionZoomIn.setText(_translate("Viewer", "Zoom in"))
        self.actionZoomIn.setShortcut(_translate("Viewer", "+"))
