[tool.poetry]
name = "webcomix"
version = "3.2.2"
description = "Webcomic downloader"
authors = ["Jean-Christophe Pelletier <pelletierj97@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.5"
click = "^7.1.1"
fake-useragent = "^0.1.11"
scrapy = "^2.0.1"
tqdm = "^4.43.0"
scrapy-splash = "^0.7.2"

[tool.poetry.dev-dependencies]
pytest = "^5.4.1"
pytest-cov = "2.5.1"
pytest-mock = "^2.0.0"
coveralls = "^1.11.1"
mypy = "^0.770"
pre-commit = "1.18.1"

[tool.poetry.scripts]
webcomix = "webcomix.cli:cli"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
