
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-03-24T19:31:54-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "3e8428f166cdf27c5c2e98a57180ddacbef5ecfb",
 "version": "1.1.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
