[tool.poetry]
name = "pydantic-vault"
version = "0.1.0a0"
description = "A simple extension to Pydantic BaseSettings that can retrieve secrets from Hashicorp Vault"
authors = ["Thomas Gaudin <thomas.gaudin@centraliens-lille.org>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/nymous/pydantic-vault"
documentation = "https://github.com/nymous/pydantic-vault"
keywords = ["hashicorp", "vault", "hvac", "pydantic"]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Programming Language :: Python :: 3 :: Only",
  "Typing :: Typed",
  "Intended Audience :: Developers",
  "Intended Audience :: Information Technology",
  "Intended Audience :: System Administrators",
  "Topic :: Software Development",
  "Topic :: Software Development :: Libraries",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Topic :: Internet",
  "Topic :: Security"
]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/nymous/pydantic-vault/issues"

[tool.poetry.dependencies]
python = "^3.6"
pydantic = "^1.0"
hvac = "^0.10.0"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
mypy = "^0.770"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
