
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-03-25T09:24:07-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "b77d7a8dcb4c11fe415d18ef56cdb398888db76a",
 "version": "0.2.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
