# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'query.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QueryDialog(object):
    def setupUi(self, QueryDialog):
        QueryDialog.setObjectName("QueryDialog")
        QueryDialog.resize(551, 457)
        self.verticalLayout = QtWidgets.QVBoxLayout(QueryDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(QueryDialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.nameEdit = QtWidgets.QLineEdit(self.frame)
        self.nameEdit.setObjectName("nameEdit")
        self.verticalLayout_2.addWidget(self.nameEdit)
        self.typeBox = QtWidgets.QComboBox(self.frame)
        self.typeBox.setObjectName("typeBox")
        self.typeBox.addItem("")
        self.typeBox.addItem("")
        self.verticalLayout_2.addWidget(self.typeBox)
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.cityEdit = QtWidgets.QLineEdit(self.groupBox)
        self.cityEdit.setObjectName("cityEdit")
        self.verticalLayout_3.addWidget(self.cityEdit)
        self.resultsList = QtWidgets.QListWidget(self.groupBox)
        self.resultsList.setObjectName("resultsList")
        self.verticalLayout_3.addWidget(self.resultsList)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.citiesList = QtWidgets.QListWidget(self.groupBox)
        self.citiesList.setObjectName("citiesList")
        self.horizontalLayout.addWidget(self.citiesList)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setObjectName("label_10")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.nbRooms = QtWidgets.QComboBox(self.frame)
        self.nbRooms.setObjectName("nbRooms")
        self.nbRooms.addItem("")
        self.nbRooms.addItem("")
        self.nbRooms.addItem("")
        self.nbRooms.addItem("")
        self.nbRooms.addItem("")
        self.nbRooms.addItem("")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nbRooms)
        self.verticalLayout_2.addLayout(self.formLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.areaMin = QtWidgets.QSpinBox(self.groupBox_3)
        self.areaMin.setMaximum(9999)
        self.areaMin.setSingleStep(5)
        self.areaMin.setObjectName("areaMin")
        self.horizontalLayout_4.addWidget(self.areaMin)
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.areaMax = QtWidgets.QSpinBox(self.groupBox_3)
        self.areaMax.setMaximum(9999)
        self.areaMax.setSingleStep(5)
        self.areaMax.setObjectName("areaMax")
        self.horizontalLayout_5.addWidget(self.areaMax)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.horizontalLayout_3.addLayout(self.formLayout)
        self.horizontalLayout_2.addWidget(self.groupBox_3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.costMin = QtWidgets.QSpinBox(self.groupBox_2)
        self.costMin.setMaximum(99999999)
        self.costMin.setSingleStep(100)
        self.costMin.setObjectName("costMin")
        self.horizontalLayout_6.addWidget(self.costMin)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.costMax = QtWidgets.QSpinBox(self.groupBox_2)
        self.costMax.setMaximum(99999999)
        self.costMax.setSingleStep(100)
        self.costMax.setObjectName("costMax")
        self.horizontalLayout_7.addWidget(self.costMax)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        self.formLayout_2.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_7)
        self.verticalLayout_4.addLayout(self.formLayout_2)
        self.horizontalLayout_2.addWidget(self.groupBox_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.frame)
        self.buttonBox = QtWidgets.QDialogButtonBox(QueryDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(QueryDialog)
        self.buttonBox.rejected.connect(QueryDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(QueryDialog)
        QueryDialog.setTabOrder(self.nameEdit, self.cityEdit)
        QueryDialog.setTabOrder(self.cityEdit, self.resultsList)
        QueryDialog.setTabOrder(self.resultsList, self.citiesList)
        QueryDialog.setTabOrder(self.citiesList, self.nbRooms)
        QueryDialog.setTabOrder(self.nbRooms, self.areaMin)
        QueryDialog.setTabOrder(self.areaMin, self.areaMax)
        QueryDialog.setTabOrder(self.areaMax, self.costMin)
        QueryDialog.setTabOrder(self.costMin, self.costMax)
        QueryDialog.setTabOrder(self.costMax, self.buttonBox)

    def retranslateUi(self, QueryDialog):
        _translate = QtCore.QCoreApplication.translate
        QueryDialog.setWindowTitle(_translate("QueryDialog", "Add a query"))
        self.label_9.setText(_translate("QueryDialog", "Name of this query:"))
        self.typeBox.setItemText(0, _translate("QueryDialog", "Rent"))
        self.typeBox.setItemText(1, _translate("QueryDialog", "Sale"))
        self.groupBox.setTitle(_translate("QueryDialog", "Cities"))
        self.label_10.setText(_translate("QueryDialog", "Number of rooms"))
        self.nbRooms.setItemText(0, _translate("QueryDialog", "N/A"))
        self.nbRooms.setItemText(1, _translate("QueryDialog", "1"))
        self.nbRooms.setItemText(2, _translate("QueryDialog", "2"))
        self.nbRooms.setItemText(3, _translate("QueryDialog", "3"))
        self.nbRooms.setItemText(4, _translate("QueryDialog", "4"))
        self.nbRooms.setItemText(5, _translate("QueryDialog", "5"))
        self.groupBox_3.setTitle(_translate("QueryDialog", "Area"))
        self.label.setText(_translate("QueryDialog", "Min"))
        self.label_2.setText(_translate("QueryDialog", "Max"))
        self.label_5.setText(_translate("QueryDialog", "m²"))
        self.label_6.setText(_translate("QueryDialog", "m²"))
        self.groupBox_2.setTitle(_translate("QueryDialog", "Cost"))
        self.label_3.setText(_translate("QueryDialog", "Min"))
        self.label_4.setText(_translate("QueryDialog", "Max"))
        self.label_7.setText(_translate("QueryDialog", "€"))
        self.label_8.setText(_translate("QueryDialog", "€"))
