- hosts: all
  name: Octavia DSVM jobs pre-run playbook
  tasks:
    - shell:
        executable: /bin/bash
        cmd: |
          set -e
          set -x
          if $(egrep --quiet '(vmx|svm)' /proc/cpuinfo) && [[ ( ! $(hostname) =~ "ovh" && ! $(hostname) =~ "limestone" ) ]]; then
              export DEVSTACK_GATE_LIBVIRT_TYPE=kvm
          fi

