[build-system]
requires = ["flit_core >=2,<3"]
build-backend = "flit_core.buildapi"

[tool.black]
line-length = 80

[tool.flit.metadata]
module = "atomic_write_path"
author = "Bao Wei"
author-email = "baowei.ur521@gmail.com"
home-page = "https://github.com/baowei521/atomic_write_path"
requires = [
    "atomicwrites >= 1.3.*",
]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
]
requires-python = ">=3.6"
keywords = "atomic write context_manager"
license = "MIT"
