language: python

os: linux

cache:
  directories:
    - $HOME/.cache/igdiscover

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda config --add channels bioconda --add channels conda-forge
  - conda info -a
  - wget https://bitbucket.org/igdiscover/testdata/downloads/igdiscover-testdata-0.6.tar.gz
  - tar xvf igdiscover-testdata-0.6.tar.gz
  - ln -s igdiscover-testdata testdata
  - "echo 'use_cache: true' > $HOME/.config/igdiscover.conf"

install:
  - conda env create -n testenv -f environment.lock.yml
  - conda install -n testenv pytest
  - source activate testenv
  - pip install .

script: pytest

env:
  global:
    - TWINE_USERNAME=__token__

jobs:
  include:
    - python: "3.7"

    - stage: deploy
      python: "3.7"
      install: python3 -m pip install twine
      if: tag IS present
      script:
        - |
          python3 setup.py sdist
          python3 -m pip wheel -w dist/ .
          ls -l dist/
          python3 -m twine upload dist/igdiscover-*
