channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - nomkl
  - python=3.7
  - seaborn=0.9.*
  - snakemake-minimal
  - cutadapt>=2.5
  - muscle
  - pear
  - flash
  - igblast=1.10
  - ruamel.yaml
  - pigz>=2.4
  - dnaio
  - xopen>=0.8.2
  - tinyalign~=0.2
