[tool.poetry]
name = "iostat-context"
version = "0.1.3"
description = "A context manager for iostat."
authors = ["Gregory C. Oakes <gregoryoakes@fastmail.com>"]
license = "GPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^2.7 || ^3.6 || ^3.7 || ^3.8 || ^3.9"
"backports.shutil_which" = {version = "^3.5.2", python = "^2.7"}
serde = "^0.8.0"

[tool.poetry.dev-dependencies]
pytest = [
    { version = "4.6", python = "<=3.4" },
    { version = "^5.2", python = ">3.4"},
]
flakehell = {version = "^0.3.3", python = ">=3.6"}
pdoc3 = {version = "^0.7.5", python = ">=3.6"}
black = {version = "^19.10b0", python = ">=3.6"}
isort = {version = "^4.3.21", python = ">=3.6"}
tox = "^3.14.5"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 88

[tool.flakehell]
max_line_length = 89

[tool.flakehell.plugins]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
