# Autogenerated by Astropy-affiliated package aiapy's setup.py on 2020-03-31 22:41:46 UTC
from __future__ import unicode_literals
import datetime

version = "0.1.0"
githash = "5fb5895f06c956e952570a4c7663880e6dadaf48"


major = 0
minor = 1
bugfix = 0

version_info = (major, minor, bugfix)

release = True
timestamp = datetime.datetime(2020, 3, 31, 22, 41, 46)
debug = False

astropy_helpers_version = "3.2.1"
