[tool.poetry]
name = "pyRclone"
version = "1.0.1"
description = "A typed interface for rclone."
authors = ["Ryan C <r.cross@lancaster.ac.uk>"]
license = "GPL-3.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
mypy = "^0.770"
pylint = "^2.2"
pytest = "^5.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
