version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
defaults: &defaults
  docker:
    - image: circleci/python:3.6

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - deps-{{ checksum "requirements.txt" }}

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          key: deps-{{ checksum "requirements.txt" }}
          paths:
            - "venv"

      - run:
          name: run flake8
          command: |
            . venv/bin/activate
            flake8 src/
            flake8 test/

      - persist_to_workspace:
          root: .
          paths:
            - .

  unittest:
    <<: *defaults

    steps:
      - attach_workspace:
          at: .

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            tox

      - codecov/upload:
          file: cov.xml

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .

      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = heavis" >> ~/.pypirc  # todo: move it to env var
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc

      - run:
          name: Build python package
          command: |
            . venv/bin/activate
            python setup.py sdist

      - run:
          name: Upload to PyPI
          command: |
            . venv/bin/activate
            twine upload dist/*

workflows:
  version: 2
  continuous-delivery:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - unittest:
          requires:
            - build
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - unittest
          filters:
            tags:
              only: /^v-[0-9]+(\.[0-9]+)*$/

            branches:
              ignore: /.*/
