repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: flake8
# - repo: https://github.com/FalconSocial/pre-commit-mirrors-pep257
#   rev: v0.3.3
#   hooks:
#     -   id: pep257
