sensor:
  - platform: ais_device_search_mqtt
    name: network_devices_info_value
    state_topic: "+/stat/#"

input_boolean:
  ais_quiet_mode:
    name: Tryb nocny
    icon: mdi:volume-off

input_datetime:
  ais_quiet_mode_start:
    name: Start trybu nocnego
    has_date: false
    has_time: true
  ais_quiet_mode_stop:
    name: Koniec trybu nocnego
    has_date: false
    has_time: true

input_select:
  assistant_voice:
    name: "Głos"
    options:
      - "Jola online"
      - "Jola lokalnie"
      - "Celina"
      - "Anżela"
      - "Asia"
      - "Sebastian"
      - "Bartek"
      - "Andrzej"
    icon: mdi:voice
    initial: "Jola lokalnie"

input_number:
  assistant_rate:
    name: "Szybkość mowy"
    min: 0.1
    max: 2
    step: 0.1
    initial: 1
  assistant_tone:
    name: "Ton mowy"
    min: 0.1
    max: 2
    step: 0.1
    initial: 1

timer:
  ais_dom_pin_join:
    name: Parowanie z bramką za pomocą PIN
    duration: 120