# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'minitorrent.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MiniTorrent(object):
    def setupUi(self, MiniTorrent):
        MiniTorrent.setObjectName("MiniTorrent")
        MiniTorrent.resize(464, 138)
        MiniTorrent.setFrameShape(QtWidgets.QFrame.StyledPanel)
        MiniTorrent.setFrameShadow(QtWidgets.QFrame.Raised)
        self.horizontalLayout = QtWidgets.QHBoxLayout(MiniTorrent)
        self.horizontalLayout.setContentsMargins(9, 5, -1, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.imageLabel = QtWidgets.QLabel(MiniTorrent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageLabel.sizePolicy().hasHeightForWidth())
        self.imageLabel.setSizePolicy(sizePolicy)
        self.imageLabel.setText("")
        self.imageLabel.setObjectName("imageLabel")
        self.horizontalLayout.addWidget(self.imageLabel)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label_5 = QtWidgets.QLabel(MiniTorrent)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.nameLabel = QtWidgets.QLabel(MiniTorrent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nameLabel.sizePolicy().hasHeightForWidth())
        self.nameLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.nameLabel.setFont(font)
        self.nameLabel.setObjectName("nameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nameLabel)
        self.label_8 = QtWidgets.QLabel(MiniTorrent)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.seedLeechLabel = QtWidgets.QLabel(MiniTorrent)
        self.seedLeechLabel.setObjectName("seedLeechLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.seedLeechLabel)
        self.label_3 = QtWidgets.QLabel(MiniTorrent)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.sizeLabel = QtWidgets.QLabel(MiniTorrent)
        self.sizeLabel.setObjectName("sizeLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.sizeLabel)
        self.label = QtWidgets.QLabel(MiniTorrent)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label)
        self.viewButton = QtWidgets.QPushButton(MiniTorrent)
        self.viewButton.setMaximumSize(QtCore.QSize(16777215, 20))
        self.viewButton.setObjectName("viewButton")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.viewButton)
        self.newTabButton = QtWidgets.QPushButton(MiniTorrent)
        self.newTabButton.setMaximumSize(QtCore.QSize(16777215, 20))
        self.newTabButton.setObjectName("newTabButton")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.newTabButton)
        self.backendButton = QtWidgets.QPushButton(MiniTorrent)
        self.backendButton.setMaximumSize(QtCore.QSize(16777215, 20))
        self.backendButton.setFlat(True)
        self.backendButton.setObjectName("backendButton")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.backendButton)
        self.horizontalLayout.addLayout(self.formLayout)

        self.retranslateUi(MiniTorrent)
        QtCore.QMetaObject.connectSlotsByName(MiniTorrent)

    def retranslateUi(self, MiniTorrent):
        _translate = QtCore.QCoreApplication.translate
        MiniTorrent.setWindowTitle(_translate("MiniTorrent", "Form"))
        self.label_5.setText(_translate("MiniTorrent", "Name"))
        self.nameLabel.setText(_translate("MiniTorrent", "TextLabel"))
        self.label_8.setText(_translate("MiniTorrent", "Seed/leech:"))
        self.seedLeechLabel.setText(_translate("MiniTorrent", "TextLabel"))
        self.label_3.setText(_translate("MiniTorrent", "Size:"))
        self.sizeLabel.setText(_translate("MiniTorrent", "TextLabel"))
        self.label.setText(_translate("MiniTorrent", "Where"))
        self.viewButton.setText(_translate("MiniTorrent", "View"))
        self.newTabButton.setText(_translate("MiniTorrent", "View in new tab"))
        self.backendButton.setText(_translate("MiniTorrent", "PushButton"))
