# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'movie.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Movie(object):
    def setupUi(self, Movie):
        Movie.setObjectName("Movie")
        Movie.resize(655, 733)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Movie.sizePolicy().hasHeightForWidth())
        Movie.setSizePolicy(sizePolicy)
        Movie.setMaximumSize(QtCore.QSize(10000, 10000))
        Movie.setFrameShape(QtWidgets.QFrame.StyledPanel)
        Movie.setFrameShadow(QtWidgets.QFrame.Raised)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(Movie)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_4 = QtWidgets.QFrame(Movie)
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 3000))
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.imageLabel = QtWidgets.QLabel(self.frame_4)
        self.imageLabel.setText("")
        self.imageLabel.setObjectName("imageLabel")
        self.verticalLayout_2.addWidget(self.imageLabel)
        self.frame_10 = QtWidgets.QFrame(self.frame_4)
        self.frame_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.castingButton = QtWidgets.QPushButton(self.frame_10)
        self.castingButton.setObjectName("castingButton")
        self.horizontalLayout_4.addWidget(self.castingButton)
        self.castingCombo = QtWidgets.QComboBox(self.frame_10)
        self.castingCombo.setObjectName("castingCombo")
        self.castingCombo.addItem("")
        self.horizontalLayout_4.addWidget(self.castingCombo)
        self.verticalLayout_2.addWidget(self.frame_10)
        self.frame_12 = QtWidgets.QFrame(self.frame_4)
        self.frame_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_11.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.torrentButton = QtWidgets.QPushButton(self.frame_12)
        self.torrentButton.setObjectName("torrentButton")
        self.horizontalLayout_11.addWidget(self.torrentButton)
        self.verticalLayout_2.addWidget(self.frame_12)
        self.frame_11 = QtWidgets.QFrame(self.frame_4)
        self.frame_11.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_10.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.subtitleButton = QtWidgets.QPushButton(self.frame_11)
        self.subtitleButton.setObjectName("subtitleButton")
        self.horizontalLayout_10.addWidget(self.subtitleButton)
        self.langCombo = QtWidgets.QComboBox(self.frame_11)
        self.langCombo.setObjectName("langCombo")
        self.horizontalLayout_10.addWidget(self.langCombo)
        self.verticalLayout_2.addWidget(self.frame_11)
        self.frame_15 = QtWidgets.QFrame(self.frame_4)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.personsInCommonButton = QtWidgets.QPushButton(self.frame_15)
        self.personsInCommonButton.setObjectName("personsInCommonButton")
        self.verticalLayout_3.addWidget(self.personsInCommonButton)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_11 = QtWidgets.QLabel(self.frame_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_15.addWidget(self.label_11)
        self.personsInCommonEdit = QtWidgets.QLineEdit(self.frame_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.personsInCommonEdit.sizePolicy().hasHeightForWidth())
        self.personsInCommonEdit.setSizePolicy(sizePolicy)
        self.personsInCommonEdit.setObjectName("personsInCommonEdit")
        self.horizontalLayout_15.addWidget(self.personsInCommonEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_15)
        self.verticalLayout_2.addWidget(self.frame_15)
        self.horizontalLayout_3.addWidget(self.frame_4)
        self.frame_3 = QtWidgets.QFrame(Movie)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 9000))
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.idFrame = QtWidgets.QFrame(self.frame_3)
        self.idFrame.setMaximumSize(QtCore.QSize(16777215, 40))
        self.idFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.idFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.idFrame.setObjectName("idFrame")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.idFrame)
        self.horizontalLayout_13.setContentsMargins(-1, 3, -1, 3)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_9 = QtWidgets.QLabel(self.idFrame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_13.addWidget(self.label_9)
        self.idEdit = QtWidgets.QLineEdit(self.idFrame)
        self.idEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.idEdit.setReadOnly(True)
        self.idEdit.setObjectName("idEdit")
        self.horizontalLayout_13.addWidget(self.idEdit)
        self.verticalLayout.addWidget(self.idFrame)
        self.frame_9 = QtWidgets.QFrame(self.frame_3)
        self.frame_9.setMaximumSize(QtCore.QSize(16777215, 35))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_7 = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_9.addWidget(self.label_7)
        self.titleLabel = QtWidgets.QLabel(self.frame_9)
        self.titleLabel.setText("")
        self.titleLabel.setObjectName("titleLabel")
        self.horizontalLayout_9.addWidget(self.titleLabel)
        self.verticalLayout.addWidget(self.frame_9)
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 35))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.durationLabel = QtWidgets.QLabel(self.frame_2)
        self.durationLabel.setText("")
        self.durationLabel.setObjectName("durationLabel")
        self.horizontalLayout_2.addWidget(self.durationLabel)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 35))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.releaseDateLabel = QtWidgets.QLabel(self.frame_6)
        self.releaseDateLabel.setText("")
        self.releaseDateLabel.setObjectName("releaseDateLabel")
        self.horizontalLayout_6.addWidget(self.releaseDateLabel)
        self.verticalLayout.addWidget(self.frame_6)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 150))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.pitchPlain = QtWidgets.QTextEdit(self.frame_5)
        self.pitchPlain.setMinimumSize(QtCore.QSize(0, 0))
        self.pitchPlain.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.pitchPlain.setObjectName("pitchPlain")
        self.horizontalLayout_5.addWidget(self.pitchPlain)
        self.verticalLayout.addWidget(self.frame_5)
        self.frame_7 = QtWidgets.QFrame(self.frame_3)
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 35))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.countryLabel = QtWidgets.QLabel(self.frame_7)
        self.countryLabel.setText("")
        self.countryLabel.setObjectName("countryLabel")
        self.horizontalLayout_7.addWidget(self.countryLabel)
        self.verticalLayout.addWidget(self.frame_7)
        self.frame_14 = QtWidgets.QFrame(self.frame_3)
        self.frame_14.setMaximumSize(QtCore.QSize(16777215, 35))
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_10 = QtWidgets.QLabel(self.frame_14)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_14.addWidget(self.label_10)
        self.genresLabel = QtWidgets.QLabel(self.frame_14)
        self.genresLabel.setText("")
        self.genresLabel.setWordWrap(True)
        self.genresLabel.setObjectName("genresLabel")
        self.horizontalLayout_14.addWidget(self.genresLabel)
        self.verticalLayout.addWidget(self.frame_14)
        self.frame = QtWidgets.QFrame(self.frame_3)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 35))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.noteLabel = QtWidgets.QLabel(self.frame)
        self.noteLabel.setText("")
        self.noteLabel.setObjectName("noteLabel")
        self.horizontalLayout.addWidget(self.noteLabel)
        self.verticalLayout.addWidget(self.frame)
        self.frame_13 = QtWidgets.QFrame(self.frame_3)
        self.frame_13.setMaximumSize(QtCore.QSize(16777215, 200))
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_8 = QtWidgets.QLabel(self.frame_13)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_12.addWidget(self.label_8)
        self.allReleasesPlain = QtWidgets.QTextEdit(self.frame_13)
        self.allReleasesPlain.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.allReleasesPlain.setObjectName("allReleasesPlain")
        self.horizontalLayout_12.addWidget(self.allReleasesPlain)
        self.verticalLayout.addWidget(self.frame_13)
        self.frame_8 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_8.sizePolicy().hasHeightForWidth())
        self.frame_8.setSizePolicy(sizePolicy)
        self.frame_8.setMaximumSize(QtCore.QSize(16777215, 200))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.frame_8)
        self.label_6.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.otherTitlesPlain = QtWidgets.QPlainTextEdit(self.frame_8)
        self.otherTitlesPlain.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.otherTitlesPlain.setObjectName("otherTitlesPlain")
        self.horizontalLayout_8.addWidget(self.otherTitlesPlain)
        self.verticalLayout.addWidget(self.frame_8)
        self.horizontalLayout_3.addWidget(self.frame_3)

        self.retranslateUi(Movie)
        QtCore.QMetaObject.connectSlotsByName(Movie)

    def retranslateUi(self, Movie):
        _translate = QtCore.QCoreApplication.translate
        Movie.setWindowTitle(_translate("Movie", "Frame"))
        self.castingButton.setText(_translate("Movie", "view casting"))
        self.castingCombo.setItemText(0, _translate("Movie", "all"))
        self.torrentButton.setText(_translate("Movie", "search torrents"))
        self.subtitleButton.setText(_translate("Movie", "search subtitles"))
        self.personsInCommonButton.setText(_translate("Movie", "Search persons in common with"))
        self.label_11.setText(_translate("Movie", "Movie ID :"))
        self.label_9.setText(_translate("Movie", "Id:"))
        self.label_7.setText(_translate("Movie", "Title:"))
        self.label_3.setText(_translate("Movie", "Duration:"))
        self.label_4.setText(_translate("Movie", "Release date:"))
        self.label_2.setText(_translate("Movie", "Pitch:"))
        self.label_5.setText(_translate("Movie", "Country:"))
        self.label_10.setText(_translate("Movie", "Genres:"))
        self.label.setText(_translate("Movie", "Note:"))
        self.label_8.setText(_translate("Movie", "All release dates:"))
        self.label_6.setText(_translate("Movie", "Other titles:"))
