# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'torrent.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Torrent(object):
    def setupUi(self, Torrent):
        Torrent.setObjectName("Torrent")
        Torrent.resize(629, 571)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Torrent.sizePolicy().hasHeightForWidth())
        Torrent.setSizePolicy(sizePolicy)
        Torrent.setMaximumSize(QtCore.QSize(10000, 10000))
        Torrent.setFrameShape(QtWidgets.QFrame.StyledPanel)
        Torrent.setFrameShadow(QtWidgets.QFrame.Raised)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(Torrent)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_3 = QtWidgets.QFrame(Torrent)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 10000))
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.idFrame = QtWidgets.QFrame(self.frame_3)
        self.idFrame.setMaximumSize(QtCore.QSize(16777215, 40))
        self.idFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.idFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.idFrame.setObjectName("idFrame")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.idFrame)
        self.horizontalLayout_13.setContentsMargins(-1, 3, -1, 3)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_9 = QtWidgets.QLabel(self.idFrame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_13.addWidget(self.label_9)
        self.idEdit = QtWidgets.QLineEdit(self.idFrame)
        self.idEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.idEdit.setReadOnly(True)
        self.idEdit.setObjectName("idEdit")
        self.horizontalLayout_13.addWidget(self.idEdit)
        self.verticalLayout.addWidget(self.idFrame)
        self.frame_9 = QtWidgets.QFrame(self.frame_3)
        self.frame_9.setMaximumSize(QtCore.QSize(16777215, 35))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_7 = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_9.addWidget(self.label_7)
        self.nameLabel = QtWidgets.QLabel(self.frame_9)
        self.nameLabel.setText("")
        self.nameLabel.setObjectName("nameLabel")
        self.horizontalLayout_9.addWidget(self.nameLabel)
        self.verticalLayout.addWidget(self.frame_9)
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 35))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.seedLeechLabel = QtWidgets.QLabel(self.frame_2)
        self.seedLeechLabel.setText("")
        self.seedLeechLabel.setObjectName("seedLeechLabel")
        self.horizontalLayout_2.addWidget(self.seedLeechLabel)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 35))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.sizeLabel = QtWidgets.QLabel(self.frame_6)
        self.sizeLabel.setText("")
        self.sizeLabel.setObjectName("sizeLabel")
        self.horizontalLayout_6.addWidget(self.sizeLabel)
        self.verticalLayout.addWidget(self.frame_6)
        self.frame_8 = QtWidgets.QFrame(self.frame_3)
        self.frame_8.setMinimumSize(QtCore.QSize(0, 150))
        self.frame_8.setMaximumSize(QtCore.QSize(16777215, 500))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.descriptionPlain = QtWidgets.QTextEdit(self.frame_8)
        self.descriptionPlain.setObjectName("descriptionPlain")
        self.horizontalLayout_8.addWidget(self.descriptionPlain)
        self.verticalLayout.addWidget(self.frame_8)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 120))
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 200))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.filesPlain = QtWidgets.QTextEdit(self.frame_5)
        self.filesPlain.setObjectName("filesPlain")
        self.horizontalLayout_5.addWidget(self.filesPlain)
        self.verticalLayout.addWidget(self.frame_5)
        self.urlFrame = QtWidgets.QFrame(self.frame_3)
        self.urlFrame.setMaximumSize(QtCore.QSize(16777215, 40))
        self.urlFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.urlFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.urlFrame.setObjectName("urlFrame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.urlFrame)
        self.horizontalLayout_7.setContentsMargins(-1, 3, -1, 3)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.urlFrame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.urlEdit = QtWidgets.QLineEdit(self.urlFrame)
        self.urlEdit.setObjectName("urlEdit")
        self.horizontalLayout_7.addWidget(self.urlEdit)
        self.verticalLayout.addWidget(self.urlFrame)
        self.magnetFrame = QtWidgets.QFrame(self.frame_3)
        self.magnetFrame.setMaximumSize(QtCore.QSize(16777215, 40))
        self.magnetFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.magnetFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.magnetFrame.setObjectName("magnetFrame")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.magnetFrame)
        self.horizontalLayout_10.setContentsMargins(-1, 3, -1, 3)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_8 = QtWidgets.QLabel(self.magnetFrame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_10.addWidget(self.label_8)
        self.magnetEdit = QtWidgets.QLineEdit(self.magnetFrame)
        self.magnetEdit.setObjectName("magnetEdit")
        self.horizontalLayout_10.addWidget(self.magnetEdit)
        self.verticalLayout.addWidget(self.magnetFrame)
        self.downloadButton = QtWidgets.QPushButton(self.frame_3)
        self.downloadButton.setObjectName("downloadButton")
        self.verticalLayout.addWidget(self.downloadButton)
        self.horizontalLayout_3.addWidget(self.frame_3)

        self.retranslateUi(Torrent)
        QtCore.QMetaObject.connectSlotsByName(Torrent)

    def retranslateUi(self, Torrent):
        _translate = QtCore.QCoreApplication.translate
        Torrent.setWindowTitle(_translate("Torrent", "Frame"))
        self.label_9.setText(_translate("Torrent", "Id:"))
        self.label_7.setText(_translate("Torrent", "Name:"))
        self.label_3.setText(_translate("Torrent", "Seed/leech:"))
        self.label_4.setText(_translate("Torrent", "Size:"))
        self.label_6.setText(_translate("Torrent", "Description:"))
        self.label_2.setText(_translate("Torrent", "Files:"))
        self.label_5.setText(_translate("Torrent", "Url:"))
        self.label_8.setText(_translate("Torrent", "Magnet:"))
        self.downloadButton.setText(_translate("Torrent", "Download"))
