
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-03-26T03:59:53+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "3a83064474b999164180f481886608165546869e",
 "version": "1.4.0.post.dev78"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
