PARAM_ID_CURRENT_KI: 3000
PARAM_ID_CURRENT_KP: 2811
PARAM_ID_CURRENT_MAX_ITERM: 268427264
PARAM_ID_CURRENT_MAX_LIMIT: 5000
PARAM_ID_CURRENT_MIN_ITERM: -268427264
PARAM_ID_CURRENT_MIN_LIMIT: -5000
PARAM_ID_POSITION_KD: 800
PARAM_ID_POSITION_KI: 0
PARAM_ID_POSITION_KP: 160
PARAM_ID_POSITION_MAX_ITERM: 98304000
PARAM_ID_POSITION_MAX_LIMIT: 2147483647
PARAM_ID_POSITION_MIN_ITERM: -98304000
PARAM_ID_POSITION_MIN_LIMIT: -2147483648
PARAM_ID_POSITION_OFFSET: 0
PARAM_ID_VELOCITY_KD: 0
PARAM_ID_VELOCITY_KI: 16000
PARAM_ID_VELOCITY_KP: 8000
PARAM_ID_VELOCITY_MAX_ITERM: 65536000
PARAM_ID_VELOCITY_MAX_LIMIT: 5000
PARAM_ID_VELOCITY_MIN_ITERM: -65536000
PARAM_ID_VELOCITY_MIN_LIMIT: -5000
