sudo: required

language: python
python:
    - '3.6'
    - '3.7'
    - '3.8'

services:
    - xvfb

addons:
    apt:
        sources:
            - sourceline: 'ppa:mc3man/mpv-tests'
        packages:
            - libdbus-glib-1-dev
            - libcairo2-dev
            - libglib2.0-dev
            - libgirepository1.0-dev
            - gir1.2-gtk-3.0
            - libmpv-dev
            - libvlc-dev
            - vlc
            - mpv

install:
    - pip3 install -U pip
    - pip3 install .[mpv,dev,external]
      # Pygobject is needed for virtual environments and Travis CI. See the
      # FAQ section in the README.
    - pip3 install pygobject
      # Both Qt bindings are installed to test them.
    - pip3 install pyqt5 pyqtwebengine pyside2

# Lint with PEP8 and run tests
script: 
      # Running the linter
    - flake8 . --ignore='F821,W503,E731'
      # Testing with both Python bindings
    - QT_API=PyQt5 python -m unittest
    - QT_API=PySide2 python -m unittest

notifications:
    email: false
