- project:
    templates:
      - check-requirements
      - openstack-cover-jobs
      - openstack-lower-constraints-jobs
      - openstack-python3-ussuri-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - sushy-tempest-ironic-partition-redfish-src
    gate:
      jobs:
        - sushy-tempest-ironic-partition-redfish-src
