version: 2
defaults: &defaults
  docker:
    - image: circleci/python:3.6

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - deps-{{ checksum "requirements.txt" }}

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - "venv"
          key: deps-{{ checksum "requirements.txt" }}

      - run:
          name: run flake8
          command: |
            . venv/bin/activate
            cd src && flake8

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            tox

  deploy:
    <<: *defaults

    steps:
      - checkout
      - restore_cache:
          key: deps-{{ checksum "requirements.txt" }}

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = heavis" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc

      - run:
          name: Build python package
          command: |
            . venv/bin/activate
            python setup.py sdist

      - run:
          name: Upload to PyPI
          command: |
            . venv/bin/activate
            twine upload dist/*

workflows:
  version: 2
  continuous-delivery:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/

      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v-[0-9]+(\.[0-9]+)*$/

            branches:
              ignore: /.*/
