
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2020-03-23T16:28:01+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "8768f61d9ef3d5a9dc7859d8df713d0add80e4fd",
 "version": "0.7.21"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
