# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: entity.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='entity.proto',
  package='schema',
  syntax='proto3',
  serialized_options=b'\n\023com.phisuite.schemaB\013EntityProtoP\001',
  serialized_pb=b'\n\x0c\x65ntity.proto\x12\x06schema\x1a\x1cgoogle/api/annotations.proto\x1a\x0c\x63ommon.proto\"d\n\x06\x45ntity\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x1e\n\x06status\x18\x03 \x01(\x0e\x32\x0e.schema.Status\x12\x1b\n\x04\x64\x61ta\x18\n \x03(\x0b\x32\r.schema.Field2\xb9\x01\n\rEntityReadAPI\x12L\n\x04List\x12\x0f.schema.Options\x1a\x0e.schema.Entity\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/schema/entity/v0/inspect0\x01\x12Z\n\x03Get\x12\x0f.schema.Options\x1a\x0e.schema.Entity\"2\x82\xd3\xe4\x93\x02,\x12*/schema/entity/v0/inspect/{name}/{version}2\x87\x03\n\x0e\x45ntityWriteAPI\x12M\n\x06\x43reate\x12\x0e.schema.Entity\x1a\x0e.schema.Entity\"#\x82\xd3\xe4\x93\x02\x1d\"\x18/schema/entity/v0/create:\x01*\x12^\n\x06Update\x12\x0e.schema.Entity\x1a\x0e.schema.Entity\"4\x82\xd3\xe4\x93\x02.\x1a)/schema/entity/v0/update/{name}/{version}:\x01*\x12`\n\x08\x41\x63tivate\x12\x0f.schema.Options\x1a\x0e.schema.Entity\"3\x82\xd3\xe4\x93\x02-2+/schema/entity/v0/activate/{name}/{version}\x12\x64\n\nDeactivate\x12\x0f.schema.Options\x1a\x0e.schema.Entity\"5\x82\xd3\xe4\x93\x02/2-/schema/entity/v0/deactivate/{name}/{version}B$\n\x13\x63om.phisuite.schemaB\x0b\x45ntityProtoP\x01\x62\x06proto3'
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,common__pb2.DESCRIPTOR,])




_ENTITY = _descriptor.Descriptor(
  name='Entity',
  full_name='schema.Entity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='schema.Entity.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='schema.Entity.version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='schema.Entity.status', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='schema.Entity.data', index=3,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=168,
)

_ENTITY.fields_by_name['status'].enum_type = common__pb2._STATUS
_ENTITY.fields_by_name['data'].message_type = common__pb2._FIELD
DESCRIPTOR.message_types_by_name['Entity'] = _ENTITY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Entity = _reflection.GeneratedProtocolMessageType('Entity', (_message.Message,), {
  'DESCRIPTOR' : _ENTITY,
  '__module__' : 'entity_pb2'
  # @@protoc_insertion_point(class_scope:schema.Entity)
  })
_sym_db.RegisterMessage(Entity)


DESCRIPTOR._options = None

_ENTITYREADAPI = _descriptor.ServiceDescriptor(
  name='EntityReadAPI',
  full_name='schema.EntityReadAPI',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=171,
  serialized_end=356,
  methods=[
  _descriptor.MethodDescriptor(
    name='List',
    full_name='schema.EntityReadAPI.List',
    index=0,
    containing_service=None,
    input_type=common__pb2._OPTIONS,
    output_type=_ENTITY,
    serialized_options=b'\202\323\344\223\002\033\022\031/schema/entity/v0/inspect',
  ),
  _descriptor.MethodDescriptor(
    name='Get',
    full_name='schema.EntityReadAPI.Get',
    index=1,
    containing_service=None,
    input_type=common__pb2._OPTIONS,
    output_type=_ENTITY,
    serialized_options=b'\202\323\344\223\002,\022*/schema/entity/v0/inspect/{name}/{version}',
  ),
])
_sym_db.RegisterServiceDescriptor(_ENTITYREADAPI)

DESCRIPTOR.services_by_name['EntityReadAPI'] = _ENTITYREADAPI


_ENTITYWRITEAPI = _descriptor.ServiceDescriptor(
  name='EntityWriteAPI',
  full_name='schema.EntityWriteAPI',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=359,
  serialized_end=750,
  methods=[
  _descriptor.MethodDescriptor(
    name='Create',
    full_name='schema.EntityWriteAPI.Create',
    index=0,
    containing_service=None,
    input_type=_ENTITY,
    output_type=_ENTITY,
    serialized_options=b'\202\323\344\223\002\035\"\030/schema/entity/v0/create:\001*',
  ),
  _descriptor.MethodDescriptor(
    name='Update',
    full_name='schema.EntityWriteAPI.Update',
    index=1,
    containing_service=None,
    input_type=_ENTITY,
    output_type=_ENTITY,
    serialized_options=b'\202\323\344\223\002.\032)/schema/entity/v0/update/{name}/{version}:\001*',
  ),
  _descriptor.MethodDescriptor(
    name='Activate',
    full_name='schema.EntityWriteAPI.Activate',
    index=2,
    containing_service=None,
    input_type=common__pb2._OPTIONS,
    output_type=_ENTITY,
    serialized_options=b'\202\323\344\223\002-2+/schema/entity/v0/activate/{name}/{version}',
  ),
  _descriptor.MethodDescriptor(
    name='Deactivate',
    full_name='schema.EntityWriteAPI.Deactivate',
    index=3,
    containing_service=None,
    input_type=common__pb2._OPTIONS,
    output_type=_ENTITY,
    serialized_options=b'\202\323\344\223\002/2-/schema/entity/v0/deactivate/{name}/{version}',
  ),
])
_sym_db.RegisterServiceDescriptor(_ENTITYWRITEAPI)

DESCRIPTOR.services_by_name['EntityWriteAPI'] = _ENTITYWRITEAPI

# @@protoc_insertion_point(module_scope)
