[tool.poetry]
name = "fakeme"
version = "0.0.0dev0"
description = "Relative Dataframes Generator: generate tables with data, that depend each other"
authors = ["xnuinside <xnuinside@gmail.com>"]
long_description = "README.md"
long_description_content_type = "text/markdown"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
ply = "^3.11"
pandas = "^1.0"
mimesis = "^4.0"

[tool.poetry.scripts]
fakeme = 'fakeme.cli:cli'

[tool.poetry.dev-dependencies]
sphinx = "^2.4"
tox = "^3.14"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
