# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'video.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Video(object):
    def setupUi(self, Video):
        Video.setObjectName("Video")
        Video.resize(647, 404)
        self.verticalLayout = QtWidgets.QVBoxLayout(Video)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleLabel = QtWidgets.QLabel(Video)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.titleLabel.setFont(font)
        self.titleLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.titleLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout.addWidget(self.titleLabel)
        self.frame = QtWidgets.QFrame(Video)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.videoPlayer = QVideoWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.videoPlayer.sizePolicy().hasHeightForWidth())
        self.videoPlayer.setSizePolicy(sizePolicy)
        self.videoPlayer.setObjectName("videoPlayer")
        self.verticalLayout_2.addWidget(self.videoPlayer)
        self.seekSlider = QtWidgets.QSlider(self.frame)
        self.seekSlider.setOrientation(QtCore.Qt.Horizontal)
        self.seekSlider.setObjectName("seekSlider")
        self.verticalLayout_2.addWidget(self.seekSlider)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(Video)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.formLayout = QtWidgets.QFormLayout(self.frame_2)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.urlEdit = QtWidgets.QLineEdit(self.frame_2)
        self.urlEdit.setEnabled(True)
        self.urlEdit.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.urlEdit.setMouseTracking(True)
        self.urlEdit.setAutoFillBackground(False)
        self.urlEdit.setReadOnly(True)
        self.urlEdit.setObjectName("urlEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.urlEdit)
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.durationLabel = QtWidgets.QLabel(self.frame_2)
        self.durationLabel.setObjectName("durationLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.durationLabel)
        self.label = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label)
        self.authorLabel = QtWidgets.QLabel(self.frame_2)
        self.authorLabel.setObjectName("authorLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.authorLabel)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.dateLabel = QtWidgets.QLabel(self.frame_2)
        self.dateLabel.setObjectName("dateLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.dateLabel)
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.ratingLabel = QtWidgets.QLabel(self.frame_2)
        self.ratingLabel.setObjectName("ratingLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.ratingLabel)
        self.verticalLayout.addWidget(self.frame_2)

        self.retranslateUi(Video)
        QtCore.QMetaObject.connectSlotsByName(Video)

    def retranslateUi(self, Video):
        _translate = QtCore.QCoreApplication.translate
        Video.setWindowTitle(_translate("Video", "Video"))
        self.titleLabel.setText(_translate("Video", "TextLabel"))
        self.label_4.setText(_translate("Video", "URL"))
        self.label_8.setText(_translate("Video", "Duration"))
        self.durationLabel.setText(_translate("Video", "TextLabel"))
        self.label.setText(_translate("Video", "Author"))
        self.authorLabel.setText(_translate("Video", "TextLabel"))
        self.label_2.setText(_translate("Video", "Date"))
        self.dateLabel.setText(_translate("Video", "TextLabel"))
        self.label_3.setText(_translate("Video", "Rating"))
        self.ratingLabel.setText(_translate("Video", "TextLabel"))
from PyQt5.QtMultimediaWidgets import QVideoWidget
