[tool.poetry]
name = "thc-net"
version = "0.1.0"
description = ""
authors = ["Hartorn <hartorn.github@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
tensorflow = "^2.1.0"
tensorflow-addons = "^0.8.3"
scikit-learn = "^0.22.2"

[tool.poetry.dev-dependencies]
pytest = "^5.3"
notebook = "^6.0.3"
ipywidgets = "^7.5.1"
wget = "^3.2"
matplotlib = "^3.2"
numpy = "^1.18" 
pandas = "^1.0" 

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"
