extraction:
  python:
    python_setup:
      version: 3
      requirements: "cython>=0.29"
  cpp:
    after_prepare:
    - "pip3 install --upgrade --user cython"
    - "pip3 install --upgrade --user wheel"
    - "export PATH=\"$HOME/.local/bin:$PATH\""
    index:
      build_command: "python3 setup.py build"
