from .git import template_git
from .hostname import template_hostname
from .input import template_input
from .path import template_path
from .prompt import template_prompt
from .pyproject import template_pyproject
from .python import template_python
from .ssh import template_ssh
from .username import template_username
from .virtualenv import template_virtualenv
from .timer import template_timer
