[tool.poetry]
name = "digiarch"
version = "0.6.0"
description = "Tools for the Digital Archive Project at Aarhus Stadsarkiv"
authors = ["Nina Jensen <jnik@aarhus.dk>", "Aarhus Stadsarkiv <stadsarkiv@aarhus.dk>"]
license = "GPL-3.0"
readme = "README.md"
homepage = "https://stadsarkiv.aarhus.dk/"
repository = "https://github.com/aarhusstadsarkiv/digiarch"
documentation = "https://digiarch.readthedocs.io/en/latest/"
keywords = ["archiving", "preservation", "digiarch"]

[tool.poetry.dependencies]
python = "^3.7"
click = "^7.0"
tqdm = "^4.36"
dacite = "^1.0"
python-dateutil = "^2.8.1"
natsort = "^7.0.1"
yaspin = "^0.16.0"
requests = "^2.23.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-cov = "^2.8"
mypy = "^0.730.0"
prospector = "^1.2.0"
black = "^19.10b0"

[tool.poetry.scripts]
digiarch = "digiarch.cli:cli"

[tool.black]
line-length = 79
exclude = ".venv"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

