[tool.poetry]
name = "empyrionbuildassistant"
version = "0.1.6"
description = "A simple set of scripts to make developing mods for Empyrion easier"
authors = ["Chris Wheeler <cmwhee@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/lostinplace/EmpyrionBuildAssistant"

[tool.poetry.dependencies]
python = "^3.8"
pathtools = "^0.1.2"
vdf = "^3.2"
watchdog = "^0.10.2"
psutil = "^5.7.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
APPLICATION-NAME = 'entry:main'
