---
features:
  - |
    Support ansible check and diff module for generate configrations. You could
    use ``EXTRA_OPTS='--check --diff' kolla-ansible genconfig`` to check what
    the configration file will be like in dry-run mode.
