# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(709, 572)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.queriesTabWidget = QtWidgets.QTabWidget(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.queriesTabWidget.sizePolicy().hasHeightForWidth())
        self.queriesTabWidget.setSizePolicy(sizePolicy)
        self.queriesTabWidget.setObjectName("queriesTabWidget")
        self.SearchTab = QtWidgets.QWidget()
        self.SearchTab.setObjectName("SearchTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.SearchTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.searchEdit = QtWidgets.QLineEdit(self.SearchTab)
        self.searchEdit.setObjectName("searchEdit")
        self.horizontalLayout.addWidget(self.searchEdit)
        self.searchButton = QtWidgets.QToolButton(self.SearchTab)
        self.searchButton.setObjectName("searchButton")
        self.horizontalLayout.addWidget(self.searchButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.jobList = QtWidgets.QListWidget(self.SearchTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jobList.sizePolicy().hasHeightForWidth())
        self.jobList.setSizePolicy(sizePolicy)
        self.jobList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.jobList.setIconSize(QtCore.QSize(128, 128))
        self.jobList.setObjectName("jobList")
        self.verticalLayout_2.addWidget(self.jobList)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.SearchTab)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.idEdit = QtWidgets.QLineEdit(self.SearchTab)
        self.idEdit.setObjectName("idEdit")
        self.horizontalLayout_2.addWidget(self.idEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.queriesTabWidget.addTab(self.SearchTab, "")
        self.advancedSearchResult = QtWidgets.QWidget()
        self.advancedSearchResult.setObjectName("advancedSearchResult")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.advancedSearchResult)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.jobListAdvancedSearch = QtWidgets.QListWidget(self.advancedSearchResult)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jobListAdvancedSearch.sizePolicy().hasHeightForWidth())
        self.jobListAdvancedSearch.setSizePolicy(sizePolicy)
        self.jobListAdvancedSearch.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.jobListAdvancedSearch.setIconSize(QtCore.QSize(128, 128))
        self.jobListAdvancedSearch.setObjectName("jobListAdvancedSearch")
        self.verticalLayout_3.addWidget(self.jobListAdvancedSearch)
        self.refreshButton = QtWidgets.QPushButton(self.advancedSearchResult)
        self.refreshButton.setObjectName("refreshButton")
        self.verticalLayout_3.addWidget(self.refreshButton)
        self.queriesTabWidget.addTab(self.advancedSearchResult, "")
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.jobFrame = QtWidgets.QFrame(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jobFrame.sizePolicy().hasHeightForWidth())
        self.jobFrame.setSizePolicy(sizePolicy)
        self.jobFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.jobFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.jobFrame.setObjectName("jobFrame")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.jobFrame)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.splitter_5 = QtWidgets.QSplitter(self.jobFrame)
        self.splitter_5.setOrientation(QtCore.Qt.Vertical)
        self.splitter_5.setObjectName("splitter_5")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.splitter_5)
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.titleLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout_6.addWidget(self.titleLabel)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.idLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.idLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.idLabel.setObjectName("idLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.idLabel)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.label_9 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.label_10 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.label_11 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.label_12 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.jobNameLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.jobNameLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.jobNameLabel.setObjectName("jobNameLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.jobNameLabel)
        self.publicationDateLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.publicationDateLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.publicationDateLabel.setObjectName("publicationDateLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.publicationDateLabel)
        self.societyNameLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.societyNameLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.societyNameLabel.setObjectName("societyNameLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.societyNameLabel)
        self.placeLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.placeLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.placeLabel.setObjectName("placeLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.placeLabel)
        self.payLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.payLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.payLabel.setObjectName("payLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.payLabel)
        self.contractTypeLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.contractTypeLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.contractTypeLabel.setObjectName("contractTypeLabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.contractTypeLabel)
        self.formationLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.formationLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.formationLabel.setObjectName("formationLabel")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.formationLabel)
        self.experienceLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.experienceLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.experienceLabel.setObjectName("experienceLabel")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.experienceLabel)
        self.urlLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.urlLabel.setOpenExternalLinks(True)
        self.urlLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.urlLabel.setObjectName("urlLabel")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.urlLabel)
        self.verticalLayout_6.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.descriptionEdit = QtWidgets.QTextEdit(self.splitter_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(50)
        sizePolicy.setHeightForWidth(self.descriptionEdit.sizePolicy().hasHeightForWidth())
        self.descriptionEdit.setSizePolicy(sizePolicy)
        self.descriptionEdit.setReadOnly(True)
        self.descriptionEdit.setObjectName("descriptionEdit")
        self.verticalLayout_31.addWidget(self.splitter_5)
        self.verticalLayout.addWidget(self.splitter_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 709, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionBackends = QtWidgets.QAction(MainWindow)
        self.actionBackends.setObjectName("actionBackends")
        self.toolBar.addAction(self.actionBackends)

        self.retranslateUi(MainWindow)
        self.queriesTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.searchButton, self.jobList)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "QHandJoob"))
        self.searchButton.setText(_translate("MainWindow", "search"))
        self.jobList.setSortingEnabled(True)
        self.label_2.setText(_translate("MainWindow", " id : "))
        self.queriesTabWidget.setTabText(self.queriesTabWidget.indexOf(self.SearchTab), _translate("MainWindow", "Search"))
        self.jobListAdvancedSearch.setSortingEnabled(True)
        self.refreshButton.setText(_translate("MainWindow", "Refresh"))
        self.queriesTabWidget.setTabText(self.queriesTabWidget.indexOf(self.advancedSearchResult), _translate("MainWindow", "Advanced search"))
        self.titleLabel.setText(_translate("MainWindow", "<h1>Loading...</h1>"))
        self.label.setText(_translate("MainWindow", "Id"))
        self.idLabel.setText(_translate("MainWindow", "Loading..."))
        self.label_3.setText(_translate("MainWindow", "Job Name"))
        self.label_5.setText(_translate("MainWindow", "Publication Date"))
        self.label_6.setText(_translate("MainWindow", "Society Name"))
        self.label_7.setText(_translate("MainWindow", "Place"))
        self.label_8.setText(_translate("MainWindow", "Pay"))
        self.label_9.setText(_translate("MainWindow", "Contract Type"))
        self.label_10.setText(_translate("MainWindow", "Formation"))
        self.label_11.setText(_translate("MainWindow", "Experience"))
        self.label_12.setText(_translate("MainWindow", "URL"))
        self.jobNameLabel.setText(_translate("MainWindow", "Loading..."))
        self.publicationDateLabel.setText(_translate("MainWindow", "Loading..."))
        self.societyNameLabel.setText(_translate("MainWindow", "Loading..."))
        self.placeLabel.setText(_translate("MainWindow", "Loading..."))
        self.payLabel.setText(_translate("MainWindow", "Loading..."))
        self.contractTypeLabel.setText(_translate("MainWindow", "Loading..."))
        self.formationLabel.setText(_translate("MainWindow", "Loading..."))
        self.experienceLabel.setText(_translate("MainWindow", "Loading..."))
        self.urlLabel.setText(_translate("MainWindow", "Loading..."))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionBackends.setText(_translate("MainWindow", "Backends"))
