[tool.poetry]
name = 'py-ts-interfaces'
version = '0.3.0'
description = 'A library that converts Python dataclasses with type annotations to a TypeScript interface and serializes them to a file.'
license = 'MIT'
authors = [
    'Christopher Cordero <ccordero@protonmail.com>'
]
readme = 'README.md'
repository = 'https://github.com/cs-cordero/py-ts-interfaces'
homepage = 'https://github.com/cs-cordero/py-ts-interfaces'
documentation = 'https://github.com/cs-cordero/py-ts-interfaces'
keywords = ['python', 'typescript', 'interfaces']

[tool.poetry.dependencies]
python = '^3.7'
astroid = '^2.3.3'

[tool.poetry.dev-dependencies]
black = '^19.10b0'
flake8 = '^3.7.9'
mypy = '^0.761'
pytest-cov = '^2.8'
pytest = "^5.3.5"
isort = "^4.3.21"

[tool.poetry.scripts]
py-ts-interfaces = "py_ts_interfaces.cli:main"
