language: python
sudo: false
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - pypy
  - pypy3

script:
  - coverage run -m zope.testrunner --test-path=src
  - sphinx-build              -b html    -d docs/_build/doctrees docs docs/_build/html
  - coverage run -a -m sphinx -b doctest -d docs/_build/doctrees docs docs/_build/doctest

after_success:
  - coveralls
notifications:
  email: false

install:
  - pip install -U pip setuptools
  - pip install -U coveralls coverage
  - pip install -U -e ".[test,docs]"


cache: pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
