
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-03-21T00:25:07+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "9a8fb676decdfcc29939c1a0d166881a30798863",
 "version": "1.4.0.post.dev16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
