[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "pytkdocs"
version = "0.1.2"
description = "Load Python objects documentation."
authors = ["Timothée Mazzucotelli <pawamoy@pm.me>"]
license = "ISC License"
readme = "README.md"
repository = "https://github.com/pawamoy/pytkdocs"
homepage = "https://github.com/pawamoy/pytkdocs"
keywords = ["python", "documentation", "docstrings", "collection"]
packages = [ { include = "pytkdocs", from = "src" } ]
include = [
    "README.md",
    "pyproject.toml"
]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
bandit = "*"
black = { version = "*", allow-prereleases = true }
coverage = "*"
flake8 = "*"
ipython = "*"
isort = { version = "*", extras = ["pyproject"] }
jinja2-cli = "*"
mkdocs = "*"
mkdocstrings = "*"
mkdocs-material = "*"
pylint = { git = "https://github.com/PyCQA/pylint" }
pytest = "*"
pytest-cov = "*"
pytest-sugar = "*"
pytest-xdist = "*"
safety = "*"

[tool.poetry.scripts]
pytkdocs = "pytkdocs.cli:main"

[tool.black]
line-length = 120

[tool.isort]
line_length = 120
not_skip = "__init__.py"
multi_line_output = 3
force_single_line = false
balanced_wrapping = true
default_section = "THIRDPARTY"
known_first_party = "pytkdocs"
include_trailing_comma = true

[tool.pylint.options]
disable = """
  bad-continuation,
  too-many-lines,
  too-many-public-methods,
  too-many-locals,
  too-many-statements,
  too-many-arguments,
  too-many-instance-attributes,
  too-many-branches,
  too-few-public-methods,
  duplicate-code
"""
max-line-length = "120"
