firmware_version:
  method: firmware_version
  name: Firmware Version
  id_name: PARAM_ID_FIRMWARE_VERSION
  unit:  ''
  message: Input parameter 

calibration_data:
  method: calibration_data
  name: Calibration Data
  id_name: PARAM_ID_CALIBRATION
  unit:  ''
  message: Input parameter

position_sys_offset:
  method: position_sys_offset
  name: System Position Offset
  id_name: PARAM_ID_POSITION_SYS_OFFSET
  unit:  ''
  message: Input parameter

