device_id:
  method: device_id
  name: Device ID
  id_name: PARAM_ID_DEVICE_ID
  unit:  ''
  message: Input parameter 

position_offset:
  method: position_offset
  name: Position Offset
  id_name: PARAM_ID_POSITION_OFFSET
  unit:  ''
  message: Input parameter

pos_KP:
  method: position_KP
  name: Position KP
  id_name: PARAM_ID_POSITION_KP
  unit: ' '
  message: Input parameter  

pos_KI:
  method: position_KI
  name: Position KI
  id_name: PARAM_ID_POSITION_KI
  unit: ' '
  message: Input parameter

pos_KD:
  method: position_KD
  name: Position KD
  id_name: PARAM_ID_POSITION_KD
  unit: ' '
  message: Input parameter

pos_min_Iterm:
  method: position_min_Iterm
  name: Position Min Iterm
  id_name: PARAM_ID_POSITION_MIN_ITERM
  unit: ' '
  message: Input parameter

pos_max_Iterm:
  method: position_max_Iterm
  name: Position Max Iterm
  id_name: PARAM_ID_POSITION_MAX_ITERM
  unit: ' '
  message: Input parameter

pos_min_limit:
  method: position_min_limit
  name: Position Min Limit
  id_name: PARAM_ID_POSITION_MIN_LIMIT
  unit: ' '
  message: Input parameter

pos_max_limit:
  method: position_max_limit
  name: Position Max Limit
  id_name: PARAM_ID_POSITION_MAX_LIMIT
  unit: ' '
  message: Input parameter
  
vel_KP:
  method: velocity_KP
  name: Velocity KP
  id_name: PARAM_ID_VELOCITY_KP
  unit: ' '
  message: Input parameter    

vel_KI:
  method: velocity_KI
  name: Velocity KI
  id_name: PARAM_ID_VELOCITY_KI
  unit: ' '
  message: Input parameter

vel_KD:
  method: velocity_KD
  name: Velocity KD
  id_name: PARAM_ID_VELOCITY_KD
  unit: ' '
  message: Input parameter

vel_min_Iterm:
  method: velocity_min_Iterm
  name: Velocity Min Iterm
  id_name: PARAM_ID_VELOCITY_MIN_ITERM
  unit: ' '
  message: Input parameter

vel_max_Iterm:
  method: velocity_max_Iterm
  name: Velocity Max Iterm
  id_name: PARAM_ID_VELOCITY_MAX_ITERM
  unit: ' '
  message: Input parameter

vel_min_limit:
  method: velocity_min_limit
  name: Velocity Min Limit
  id_name: PARAM_ID_VELOCITY_MIN_LIMIT
  unit: ' '
  message: Input parameter  

vel_max_limit:
  method: velocity_max_limit
  name: Velocity Max Limit
  id_name: PARAM_ID_VELOCITY_MAX_LIMIT
  unit: ' '
  message: Input parameter

cur_KI:
  method: current_KI
  name: Current KI
  id_name: PARAM_ID_CURRENT_KI
  unit:  ''
  message: Input parameter

cur_KP:
  method: current_KP
  name: Current KP
  id_name: PARAM_ID_CURRENT_KP
  unit:  ''
  message: Input parameter  

cur_min_Iterm:
  method: current_min_Iterm
  name: Current Min Iterm
  id_name: PARAM_ID_CURRENT_MIN_ITERM
  unit: ''
  message: Input parameter

cur_max_Iterm:
  method: current_max_Iterm
  name: Current Max Iterm
  id_name: PARAM_ID_CURRENT_MAX_ITERM
  unit: '' 
  message: Input parameter

cur_min_limit:
  method: current_min_limit
  name: Current Min Limit
  id_name: PARAM_ID_CURRENT_MIN_LIMIT
  unit: ' '
  message: Input parameter

cur_max_limit:
  method: current_max_limit
  name: Current Max Limit
  id_name: PARAM_ID_CURRENT_MAX_LIMIT
  unit: ' '
  message: Input parameter  

