[tool.poetry]
name = "libdiff"
version = "0.1.0"
description = ""
authors = ["Lee Suho <riemannulus@hitagi.moe>"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
Sphinx = "^2.4.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
