[tool.poetry]
name = "awsfind"
version = "0.4.0"
description = "searches across all accounts and regions known to chaim for the item(s)"
authors = ["ccdale <chris.allison@hivehome.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.6"
chaim = "^0.8.0"
boto3 = "^1.11.9"
toml = "^0.10.0"
ccautils = "^0.4.2"
ccaaws = "^0.4.6"
ccalogging = "^0.3.3"

[tool.poetry.dev-dependencies]
pytest = "^5.3.5"
sphinx = "^2.3.1"
recommonmark = "^0.6.0"

[tool.poetry.scripts]
ifind = "awsfind.find:awsFindInstances"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
