
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-03-24T13:22:44+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "09ab6a29f6b0c0b3454d8758a8c363a5c959a871",
 "version": "0.8.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
