matrix:
  include:
    # - os: linux
    #   compiler: clang
    #   env: CFLAGS="-fsanitize=memory -fno-omit-frame-pointer"
    - os: linux
      compiler: clang
      env: CFLAGS="-fsanitize=address -fno-omit-frame-pointer"
    - os: linux
      compiler: clang
      env: CFLAGS="-fsanitize=undefined -fno-omit-frame-pointer"
    - os: linux
      compiler: clang
      env: CFLAGS="-fsanitize=thread -fno-omit-frame-pointer"
    - os: linux
      compiler: gcc
    - os: osx

language: C

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get install liblapack-dev;
    fi

script:
  # Use -O0 for santizers to work.
  - make OPT=-O0
  - make test OPT=-O0
  - test/run_tests
  - sudo make install OPT=-O0

notifications:
  email:
    - bodonoghue85@gmail.com

