[tool.poetry]
name = "gtk-recurrence-popover"
version = "5.0.0"
description = "A Gtk Popover for todo apps that allows you to select recurrence settings"
authors = ["BeatLink <beatlink@protonmail.com>"]
license = "GPL-3.0+"

packages = [{include = "recurrence_popover"}]

[tool.poetry.dependencies]
python = "^3.6"
pygobject = "^3.32.2"
task-recurrence = "^3.0.0"
gtk-datetime-popover = "^6.0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
