default_session_data_timeout: 0
deployment:
  api_gateway_id: k861yne584
messages:
  database_client: dynamodb
  dynamodb:
    region_name: eu-west-3
    table_name: skill_hello-world_messages
  use_database_dynamic_messages: true
sessions_users_data:
  database_client: dynamodb
  dynamodb:
    region_name: eu-west-3
    table_name: skill_hello-world_users-data
