
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-03-16T16:26:23-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "32be6dabd4bb6ec683b8b234a78ea068ff451ed9",
 "version": "0.4.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
