---
# https://packit.dev/docs/configuration/#top-level-keys
downstream_package_name: python-ogr
upstream_project_url: https://github.com/packit-service/ogr
# the version is different than with basic git describe
create_tarball_command: ["python3", "setup.py", "sdist", "--dist-dir", "."]
current_version_command: ["python3", "setup.py", "--version"]
jobs:
  - job: sync_from_downstream
    trigger: commit
  - job: propose_downstream
    trigger: release
    metadata:
      dist-git-branch: fedora-all
  - job: copr_build
    trigger: pull_request
    metadata:
      targets:
        - fedora-all
  - job: tests
    trigger: pull_request
    metadata:
      targets:
        - fedora-all
