# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/builds/clients/python/sakia/src/sakia/gui/sub/transfer/transfer.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TransferMoneyWidget(object):
    def setupUi(self, TransferMoneyWidget):
        TransferMoneyWidget.setObjectName("TransferMoneyWidget")
        TransferMoneyWidget.resize(479, 511)
        self.verticalLayout = QtWidgets.QVBoxLayout(TransferMoneyWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupbox_connection = QtWidgets.QGroupBox(TransferMoneyWidget)
        self.groupbox_connection.setObjectName("groupbox_connection")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupbox_connection)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.combo_connections = QtWidgets.QComboBox(self.groupbox_connection)
        self.combo_connections.setObjectName("combo_connections")
        self.horizontalLayout_4.addWidget(self.combo_connections)
        self.verticalLayout.addWidget(self.groupbox_connection)
        self.group_box_recipient = QtWidgets.QGroupBox(TransferMoneyWidget)
        self.group_box_recipient.setObjectName("group_box_recipient")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.group_box_recipient)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radio_pubkey = QtWidgets.QRadioButton(self.group_box_recipient)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_pubkey.sizePolicy().hasHeightForWidth())
        self.radio_pubkey.setSizePolicy(sizePolicy)
        self.radio_pubkey.setChecked(False)
        self.radio_pubkey.setObjectName("radio_pubkey")
        self.horizontalLayout.addWidget(self.radio_pubkey)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.edit_pubkey = QtWidgets.QLineEdit(self.group_box_recipient)
        self.edit_pubkey.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_pubkey.sizePolicy().hasHeightForWidth())
        self.edit_pubkey.setSizePolicy(sizePolicy)
        self.edit_pubkey.setInputMask("")
        self.edit_pubkey.setText("")
        self.edit_pubkey.setObjectName("edit_pubkey")
        self.horizontalLayout.addWidget(self.edit_pubkey)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.layout_search_user = QtWidgets.QHBoxLayout()
        self.layout_search_user.setContentsMargins(-1, 6, -1, -1)
        self.layout_search_user.setObjectName("layout_search_user")
        self.radio_search = QtWidgets.QRadioButton(self.group_box_recipient)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_search.sizePolicy().hasHeightForWidth())
        self.radio_search.setSizePolicy(sizePolicy)
        self.radio_search.setObjectName("radio_search")
        self.layout_search_user.addWidget(self.radio_search)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.layout_search_user.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.layout_search_user)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radio_local_key = QtWidgets.QRadioButton(self.group_box_recipient)
        self.radio_local_key.setObjectName("radio_local_key")
        self.horizontalLayout_2.addWidget(self.radio_local_key)
        self.combo_local_keys = QtWidgets.QComboBox(self.group_box_recipient)
        self.combo_local_keys.setObjectName("combo_local_keys")
        self.horizontalLayout_2.addWidget(self.combo_local_keys)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.radio_contacts = QtWidgets.QRadioButton(self.group_box_recipient)
        self.radio_contacts.setObjectName("radio_contacts")
        self.horizontalLayout_6.addWidget(self.radio_contacts)
        self.combo_contacts = QtWidgets.QComboBox(self.group_box_recipient)
        self.combo_contacts.setObjectName("combo_contacts")
        self.horizontalLayout_6.addWidget(self.combo_contacts)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout.addWidget(self.group_box_recipient)
        self.frame = QtWidgets.QFrame(TransferMoneyWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_total = QtWidgets.QLabel(self.frame)
        self.label_total.setObjectName("label_total")
        self.verticalLayout_8.addWidget(self.label_total)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.spinbox_relative = QtWidgets.QDoubleSpinBox(self.frame)
        self.spinbox_relative.setDecimals(6)
        self.spinbox_relative.setMaximum(1e+23)
        self.spinbox_relative.setSingleStep(0.01)
        self.spinbox_relative.setObjectName("spinbox_relative")
        self.horizontalLayout_3.addWidget(self.spinbox_relative)
        self.spinbox_amount = QtWidgets.QDoubleSpinBox(self.frame)
        self.spinbox_amount.setWrapping(False)
        self.spinbox_amount.setFrame(True)
        self.spinbox_amount.setReadOnly(False)
        self.spinbox_amount.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinbox_amount.setProperty("showGroupSeparator", False)
        self.spinbox_amount.setDecimals(2)
        self.spinbox_amount.setSingleStep(1.0)
        self.spinbox_amount.setProperty("value", 0.0)
        self.spinbox_amount.setObjectName("spinbox_amount")
        self.horizontalLayout_3.addWidget(self.spinbox_amount)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.frame)
        self.groupBox_3 = QtWidgets.QGroupBox(TransferMoneyWidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.edit_message = QtWidgets.QLineEdit(self.groupBox_3)
        self.edit_message.setInputMask("")
        self.edit_message.setObjectName("edit_message")
        self.verticalLayout_3.addWidget(self.edit_message)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox = QtWidgets.QGroupBox(TransferMoneyWidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.layout_password_input = QtWidgets.QHBoxLayout()
        self.layout_password_input.setObjectName("layout_password_input")
        self.verticalLayout_2.addLayout(self.layout_password_input)
        self.verticalLayout.addWidget(self.groupBox)
        self.button_box = QtWidgets.QDialogButtonBox(TransferMoneyWidget)
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.verticalLayout.addWidget(self.button_box)

        self.retranslateUi(TransferMoneyWidget)
        QtCore.QMetaObject.connectSlotsByName(TransferMoneyWidget)

    def retranslateUi(self, TransferMoneyWidget):
        _translate = QtCore.QCoreApplication.translate
        TransferMoneyWidget.setWindowTitle(_translate("TransferMoneyWidget", "Form"))
        self.groupbox_connection.setTitle(_translate("TransferMoneyWidget", "Select account"))
        self.group_box_recipient.setTitle(_translate("TransferMoneyWidget", "Transfer money to"))
        self.radio_pubkey.setText(_translate("TransferMoneyWidget", "&Recipient public key"))
        self.edit_pubkey.setPlaceholderText(_translate("TransferMoneyWidget", "Key"))
        self.radio_search.setText(_translate("TransferMoneyWidget", "Search &user"))
        self.radio_local_key.setText(_translate("TransferMoneyWidget", "Local ke&y"))
        self.radio_contacts.setText(_translate("TransferMoneyWidget", "Con&tact"))
        self.label_total.setText(_translate("TransferMoneyWidget", "Available money: "))
        self.label_3.setText(_translate("TransferMoneyWidget", "Amount"))
        self.spinbox_relative.setSuffix(_translate("TransferMoneyWidget", " UD"))
        self.groupBox_3.setTitle(_translate("TransferMoneyWidget", "Transaction message"))
        self.groupBox.setTitle(_translate("TransferMoneyWidget", "Secret Key / Password"))

