
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-03-27T12:55:00-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "28079f3a7ff6219472f8b778d7f6627bfd551cef",
 "version": "0.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
