language: python
matrix:
  include:
  - python: '3.6'
    env: REQUIREMENTS="latest"
before_install:
# Work around https://github.com/travis-ci/travis-ci/issues/7940
- export BOTO_CONFIG=/dev/null
services:
- docker
install:
- make build
script:
- make flake8
- make testsnocov  # Disable coverage tests because of Travis
after_success:
- coveralls
deploy:
  provider: pypi
  skip_existing: true
  user: victorng
  distributions: sdist bdist_wheel
  password:
    secure: W1v01fF61QCnLaRk1GVUIJw0OajURyCE8ORIHhnmeptLR6Cg0HIdO9SX0wqysxN7ANs0WK7yuuKAcBWUufSTgyNri804Ajsu1YVURnYGJzd9gsXPAGKNaHOHr8J008XYOmQvi8DLdtWFOitM8ipxfISNPeV/fFlk7Lq95IPL8eFasnQNzJyG3tgO5hDmW3L/0AF1XLbjh3WZmXkCtl6y76NJb4TYK8+4JNV8LgoLIowyjYH4qlrdhQgfmjZWJqSwfO3fgWQnHOu2bMshb75dUn1GUPNRSFk/4Xel3Nbzgzyh3OQifg9BEukiwjMqN5vdsIZYZd7I3+OYwKvNfhLomz5l1ujBvZ4Guip8+SiV6OTSiJoHshv3UFlffRCTDxCE54yVR6bU/RF64zZLnYoZ0b8lHzMYP74S6C/V87VJf0wIGo9hTB2sORfW6eIHgQnQnWeC30EcwYUbxuoXd0xEnYcxApiNr/O3AVGuyHHR93/lGpEJHd7LKoeQNZvIBNc/mBCplmKKZgZWDA6eAZHA6bsPI1FsqDjWxjFGlMuBsoSWikBBFfWTX65pICI0xs3BTCfOp/35XsDyYJJ+UiJcq8Rk/vEHGeVePHuN59ZN543NCVbc5npwumHYI+/JhLD3ogEbl2BG4lxz0E/f/le1JMKpzAXbCkALyTyee7C2DWo=
  on:
    tags: true
    repo: mozilla/taar
