language: python
cache: pip

arch:
  - ppc64le
  - arm64
  - s390x

python:
  - "2.7"
  - "3.5"
  - "3.8"
  - "3.9-dev"

jobs:
  fast_finish: true

install:
  - pip install -U pip
  - pip install -U pytest six
  - pip install .

script: pytest
