[tool.poetry]
name = "wagtail-meilisearch"
version = "0.1.0"
description = "A MeiliSearch backend for Wagatil"
authors = ["Hactar <systems@hactar.is>"]

[tool.poetry.dependencies]
python = "^3.6"

meilisearch = "^0.9.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
