[tool.poetry]
name = "toqito"
version = "0.0.1"
description = "General purpose Python tools for the study of quantum information."
authors = [
    "Vincent Russo <vincentrusso1@gmail.com>"
]
maintainers = [
    "Vincent Russo <vincentrusso1@gmail.com>"
]
readme = "README.md"
repository = "https://github.com/vprusso/toqito"
keywords = ["quantum information", "quantum computing"]


[tool.poetry.dependencies]
python = "^3.7"
cvx = "*"
cvxpy = "1.1.0a3"
numpy = "*"
picos = "*"
scipy = "*"
scikit-image = "*"

[tool.poetry.dev-dependencies]
flake8 = "^3.7"
flake8-docstrings = "^1.5"
nose = "^1.3"
pep8 = "^1.7"
pylint = "^2.4"
mypy = "^0.750.0"
coverage = "^4.5"
coveralls = "^1.9"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
