[tool.poetry]
name = "django-cookiebanner"
version = "0.1.0"
description = ""
authors = ["Andreas Nüßlein <andreas@nuessle.in>"]
readme = "README.md"
keywords = ["django", "cookie", "gdpr", "dsgvo"]

packages = [
  {include = "cookiebanner"}
]
[tool.poetry.dependencies]
python = "^3.6"
django = ">=1.11"

[tool.poetry.dev-dependencies]
pytest-django = "*"
pytest-cov = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
