# coding: utf-8

"""
    Toshl

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import toshl_swagger_client
from toshl_swagger_client.models.me_pro_trial import MeProTrial  # noqa: E501
from toshl_swagger_client.rest import ApiException


class TestMeProTrial(unittest.TestCase):
    """MeProTrial unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMeProTrial(self):
        """Test MeProTrial"""
        # FIXME: construct object with mandatory attributes with example values
        # model = toshl_swagger_client.models.me_pro_trial.MeProTrial()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
