
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-03-31T22:33:58+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "082d1277ae5cbc65f3ad0f28c3241e2996b2f8a4",
 "version": "3.1.15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
