[build-system]
build-backend = "flit_core.buildapi"
requires = [ "flit_core >=2,<3",]


[tool.black]
line-length = 100


[tool.flit.metadata]
module = "atomic_write_path"
author = "Bao Wei"
author-email = "baowei.ur521@gmail.com"
requires = ["atomicwrites >= 1.3"]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
]
requires-python = ">=3.6"
keywords = "atomic write context-manager"
license = "MIT"


[tool.nitpick]
style = "https://raw.githubusercontent.com/dycw/nitpick/master/nitpick-style.toml"
