[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "git-changelog"
version = "0.3.0"
description = "Automatic Changelog generator using Jinja2 templates."
authors = ["Timothée Mazzucotelli <pawamoy@pm.me>"]
license = "ISC"
readme = "README.md"
repository = "https://github.com/pawamoy/git-changelog"
homepage = "https://github.com/pawamoy/git-changelog"
keywords = ["git", "changelog", "changelog-generator", "commit-style", "commit-convention"]
packages = [ { include = "git_changelog", from = "src" } ]
include = [
    "README.md",
    "pyproject.toml"
]

[tool.poetry.dependencies]
python = "^3.6"
Jinja2 = "^2.10"

[tool.poetry.dev-dependencies]
bandit = "^1.5"
black = "^19.10b0"
coverage = "^5.0.4"
cruft = "^1.1"
flake8 = "^3.7"
ipython = "^7.3"
isort = { version = "^4.3", extras = ["pyproject"] }
jinja2-cli = "^0.7.0"
mypy = "^0.770"
pylint = { git = "https://github.com/PyCQA/pylint.git" }
pytest = "^4.3"
pytest-cov = "^2.8"
pytest-sugar = "^0.9.2"
pytest-xdist = "^1.26"
recommonmark = "^0.6.0"
safety = "^1.8"
sphinx = "^1.8"
sphinx-rtd-theme = "^0.4.3"
toml = "^0.10.0"

[tool.poetry.scripts]
git-changelog = "git_changelog.cli:main"

[tool.black]
line-length = 120

[tool.isort]
line_length = 120
not_skip = "__init__.py"
multi_line_output = 3
force_single_line = false
balanced_wrapping = true
default_section = "THIRDPARTY"
known_first_party = "git_changelog"
include_trailing_comma = true

[tool.pylint.options]
disable = """
  bad-continuation,
  too-many-lines,
  too-many-public-methods,
  too-many-locals,
  too-many-statements,
  too-many-arguments,
  too-many-instance-attributes,
  too-many-branches,
  too-few-public-methods,
  duplicate-code
"""
max-line-length = "120"
