dist: xenial
services:
  - xvfb
addons:
  chrome: stable
language: python
python:
  - "2.7"
  - "3.5"
env:
  global:
    - DEFAULT_CHROME_BROWSER_PATH=google-chrome-stable
  matrix:
    - CONFIG=unit
    - CONFIG=integration
    - CONFIG=e2e
install:
  - pip install -r dev_requirements.txt
script:
  - ./scripts/travis.sh -t $CONFIG