auto: no
dry-run: no
write: yes
threads: 1
force: no
quiet: no
items_per_run: 0
keep_output: no
keep_profiles: no
low_level_targets:
  average_loudness:
    path: "lowlevel.average_loudness"
    type: float
    required: yes
  bpm:
    path: "rhythm.bpm"
    type: integer
    required: yes
  danceability:
    path: "rhythm.danceability"
    type: float
  beats_count:
    path: "rhythm.beats_count"
    type: integer
high_level_targets:
  danceable:
    path: "highlevel.danceability.all.danceable"
    type: float
    required: yes
  gender:
    path: "highlevel.gender.value"
    type: string
    required: yes
  is_male:
    path: "highlevel.gender.all.male"
    type: float
  is_female:
    path: "highlevel.gender.all.female"
    type: float
  genre_rosamerica:
    path: "highlevel.genre_rosamerica.value"
    type: string
    required: yes
  voice_instrumental:
    path: "highlevel.voice_instrumental.value"
    type: string
    required: yes
  is_voice:
    path: "highlevel.voice_instrumental.all.voice"
    type: float
  is_instrumental:
    path: "highlevel.voice_instrumental.all.instrumental"
    type: float
  mood_acoustic:
    path: "highlevel.mood_acoustic.all.acoustic"
    type: float
    required: yes
  mood_aggressive:
    path: "highlevel.mood_aggressive.all.aggressive"
    type: float
    required: yes
  mood_electronic:
    path: "highlevel.mood_electronic.all.electronic"
    type: float
    required: yes
  mood_happy:
    path: "highlevel.mood_happy.all.happy"
    type: float
    required: yes
  mood_party:
    path: "highlevel.mood_party.all.party"
    type: float
    required: yes
  mood_relaxed:
    path: "highlevel.mood_relaxed.all.relaxed"
    type: float
    required: yes
  mood_sad:
    path: "highlevel.mood_sad.all.sad"
    type: float
    required: yes
low_level_extractor: /your/path/to/streaming_extractor_music
high_level_extractor: /your/path/to/streaming_extractor_music_svm
low_level_profile:
  outputFormat: json
  outputFrames: 0
high_level_profile:
  outputFormat: json
  highlevel:
    compute: 1
    svm_models:
      - /your/path/to/danceability.history
      - /your/path/to/gender.history
      - /your/path/to/genre_rosamerica.history
      - /your/path/to/mood_acoustic.history
      - /your/path/to/mood_aggressive.history
      - /your/path/to/mood_electronic.history
      - /your/path/to/mood_happy.history
      - /your/path/to/mood_party.history
      - /your/path/to/mood_relaxed.history
      - /your/path/to/mood_sad.history
      - /your/path/to/voice_instrumental.history
chromaprint:
  compute: 0