
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-03-20T17:16:55-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "ae64b2df8fbdad33ae79393ad09d97bca16d5655",
 "version": "v0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
