name: Docker Images

on:
  push:
    paths:
      - ".docker/*"
      - ".github/workflows/docker.yml"
  pull_request:
    paths:
      - ".docker/*"
      - ".github/workflows/docker.yml"
  schedule:
    # Execute a weekly build on Monday at 2AM UTC
    - cron:  '0 2 * * 1'

jobs:
  docker:
    name: 'diegoferigo/gym-ignition:${{ matrix.tag }}'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        baseimage: ['ubuntu:bionic']
        tag:
          - ci-master
          - ci-devel
          - pypi-master
          - pypi-devel
          - latest
          - nightly
        include:
          - tag: nightly
            extra_docker_options: |
              --build-arg pypi_package='gym-ignition-nightly' --build-arg branch='devel' \

    steps:
      - uses: actions/checkout@master
        if: github.event_name != 'schedule'

      - uses: actions/checkout@master
        with:
          ref: 'refs/heads/devel'
        if: github.event_name == 'schedule'

      - name: Build
        env:
          TAG: ${{ matrix.tag }}
        run: |
          cd .docker/
          docker build . \
            --pull --build-arg from=${{ matrix.baseimage }} \
            --rm -t diegoferigo/gym-ignition:${TAG} \
            ${{ matrix.extra_docker_options }} \
            -f Dockerfile.${TAG%-*}

      - name: Login
        if: |
          github.repository == 'robotology/gym-ignition' &&
          github.event_name != 'pull_request' &&
          (github.event_name == 'schedule' || github.ref == 'refs/heads/devel')
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin

      - name: Push
        if: |
          github.repository == 'robotology/gym-ignition' &&
          github.event_name != 'pull_request' &&
          (github.event_name == 'schedule' || github.ref == 'refs/heads/devel')
        run: docker push diegoferigo/gym-ignition:${{ matrix.tag }}
