auto: no
dry-run: no
write: yes
threads: 1
force: no
quiet: no
low_level_targets:
    average_loudness:
        path: "lowlevel.average_loudness"
        type: float
    bpm:
        path: "rhythm.bpm"
        type: integer
    danceability:
        path: "rhythm.danceability"
        type: float
    beats_count:
        path: "rhythm.beats_count"
        type: integer
high_level_targets:
    danceable:
        path: "highlevel.danceability.all.danceable"
        type: float
    gender:
        path: "highlevel.gender.value"
        type: string
    is_male:
        path: "highlevel.gender.all.male"
        type: float
    is_female:
        path: "highlevel.gender.all.female"
        type: float
    genre_rosamerica:
        path: "highlevel.genre_rosamerica.value"
        type: string
    voice_instrumental:
        path: "highlevel.voice_instrumental.value"
        type: string
    is_voice:
        path: "highlevel.voice_instrumental.all.voice"
        type: float
    is_instrumental:
        path: "highlevel.voice_instrumental.all.instrumental"
        type: float
    mood_acoustic:
        path: "highlevel.mood_acoustic.all.acoustic"
        type: float
    mood_aggressive:
        path: "highlevel.mood_aggressive.all.aggressive"
        type: float
    mood_electronic:
        path: "highlevel.mood_electronic.all.electronic"
        type: float
    mood_happy:
        path: "highlevel.mood_happy.all.happy"
        type: float
    mood_party:
        path: "highlevel.mood_party.all.party"
        type: float
    mood_relaxed:
        path: "highlevel.mood_relaxed.all.relaxed"
        type: float
    mood_sad:
        path: "highlevel.mood_sad.all.sad"
        type: float
