# You should not use special characters in the value keys
#
# A single whitespace in `line` will match any number of whitespaces. You should be explicit when
# Matching white space in `values`
#
prefixes:
  - time_format: "%b %d %H:%M:%S"
    values:
      date: (\w+\s+\d+)
      time: (\d\d:\d\d:\d\d)
      hostPrefix: (re\d.)?
      host: ([^ ]+)
      processName: /?(\w+)
      # Most log lines have a process ID, however some do not
      processId: \[?(\d+)?\]?
      tag: ([\w\s]+)
    line: '{date} {time} {hostPrefix}{host} {processName}{processId}: {tag}:'
  - time_format: "%b %d %H:%M:%S"
    values:
      date: (\w+\s+\d+)
      time: (\d\d:\d\d:\d\d)
      hostPrefix: (re\d.)?
      host: ([^ ]+)
      tag: (\w+)
      # Most log lines have a process ID, however some do not
      processId: (\d+)
    line: '{date} {time} {hostPrefix}{host} {tag}[{processId}]:'
  - time_format: "%b %d %H:%M:%S"
    values:
      date: (\w+\s+\d+)
      time: (\d\d:\d\d:\d\d)
      hostPrefix: (re\d.)?
      host: ([^ ]+)
      fpcId: (\d+)
      tag: (\w+)
      # Some logs have data which can be inside brackets or parenthesis
      additionalData: (?:(?:\[|\()(.+)(?:\]|\)))?
    line: '{date} {time} {hostPrefix}{host} fpc{fpcId} {tag}{additionalData}:'
  # The following matches dcpfe specific logs
  - time_format: "%b %d %H:%M:%S"
    values:
      date: (\w+\s+\d+)
      time: (\d\d:\d\d:\d\d)
      hostPrefix: (re\d.)?
      host: ([^ ]+)
      fpcId: (\d+)
      fpcId2: (\d+)
      tag: (\w+)
      # Some logs have data which can be inside brackets or parenthesis
      additionalData: (?:(?:\[|\()(.+)(?:\]|\)))?
    line: '{date} {time} {hostPrefix}{host} fpc{fpcId} fpc{fpcId2} dcpfe: {tag}{additionalData}:'
