---
data:
  project_dir: ""
  train:
    paths:
      - "data/train.txt"
  eval:
    paths:
      - "data/test.txt"
  infer:
    paths:
      - "data/test.txt"

    infer_no_label: False
  task:
    type: Classification
    name: TextMatchTask
    preparer:
      enable: true
      name: TextMatchPreparer
      done_sign: "exp/prepare.done"
      reuse: false
    use_dense: false
    language: english
    clean_english: True
    vocab_min_frequency: 0
    split_by_space: false
    use_word: true
    use_custom_vocab: true
    text_vocab: "data/text_vocab.txt"
    label_vocab: "exp/label_vocab.txt"
    max_seq_len: 42
    num_parallel_calls: 12
    num_prefetch_batch: 2
    shuffle_buffer_size: 15000
    need_shuffle: true
    batch_size: 30
    epochs: 2
    classes:
      positive_id: 1
      num_classes: 2
      vocab:
        0: 0
        1: 1


model:
  name: MatchRnnTextClassModel
  type: keras
  use_pre_train_emb: false
  pre_train_emb_path: ""
  embedding_path: "exp/embeding.pkl"

  net:
    structure:
      embedding_size: 200
      emb_trainable: true
      cell_type: gru
      cell_dim: 100
      lstm_num_units: 256  #256
      fc_num_units: 100  #100
      dropout_rate: 0.2
      l2_reg_lambda: 4e-6
      activate: relu
      sent_hidden_size: 300

solver:
  name: RawMatchSolver
  adversarial:
    enable: false # whether to using adversiral training
    adv_alpha: 0.5 # adviseral alpha of loss
    adv_epslion: 0.1 # adviseral example epslion
  model_average:
    enable: false # use average model
    var_avg_decay: 0.99 # the decay rate of varaibles
  optimizer:
    name: adam
    loss: CrossEntropyLoss 
    label_smoothing: 0.0 # label smoothing rate
    learning_rate:
      rate: 0.0001 # learning rate of Adam optimizer
      type:  exp_decay # learning rate type
      decay_rate: 0.99  # the lr decay rate
      decay_steps: 100  # the lr decay_step for optimizer
    clip_global_norm: 3.0 # clip global norm
  metrics:
    pos_label: 1 # int, same to sklearn
    cals:
      - name: AccuracyCal
        arguments: Null
      - name: PrecisionCal
        arguments:
          average: 'macro'
      - name: RecallCal
        arguments:
          average: 'macro'
      - name: F1ScoreCal
        arguments:
          average: 'weighted'
  postproc:
    name: SavePredPostProc
    res_file: "exp/text-match/res.txt"
  saver:
    model_path: "exp/text-match/ckpt"
    max_to_keep: 30 #30
    save_checkpoint_steps: 10 #100
    print_every: 10
  service:
    model_path: "exp/text-match/service"
    model_version: "1"
  run_config:
    tf_random_seed: null
    allow_soft_placement: true
    log_device_placement: false
    intra_op_parallelism_threads: 10
    inter_op_parallelism_threads: 10
    allow_growth: true

